apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        add_header X-Test "chart-test-swarm";
    creationTimestamp: "2026-05-31T01:34:53Z"
    generation: 1
    name: sample-snippet
    namespace: sample
    resourceVersion: "623"
    uid: 8360b7d8-e258-4493-a120-aa7a8558a661
  spec:
    ingressClassName: nginx
    rules:
    - host: sample.test.local
      http:
        paths:
        - backend:
            service:
              name: sample
              port:
                number: 80
          path: /
          pathType: Prefix
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
