apiVersion: v1
items:
- apiVersion: v1
  data:
    ca-crl.pem: ""
  kind: ConfigMap
  metadata:
    creationTimestamp: "2026-06-09T14:18:57Z"
    labels:
      istio.io/config: "true"
    name: istio-ca-crl
    namespace: sample
    resourceVersion: "625"
    uid: 80dd58c1-7247-45fa-b401-195eec2bb80d
- apiVersion: v1
  data:
    root-cert.pem: |
      -----BEGIN CERTIFICATE-----
      MIIC/TCCAeWgAwIBAgIRAJdtwwoGcWJiJu1/XOz5eV8wDQYJKoZIhvcNAQELBQAw
      GDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDAeFw0yNjA2MDkxNDE4NTFaFw0zNjA2
      MDYxNDE4NTFaMBgxFjAUBgNVBAoTDWNsdXN0ZXIubG9jYWwwggEiMA0GCSqGSIb3
      DQEBAQUAA4IBDwAwggEKAoIBAQDE1/glIVieB7NhbVLyg9cUyANfYtbx/z3LH3eR
      Fxa62zhKedpur1lg+zn5czhWPMEIXus/x1KOHUvNz9jNl+6PvKV+6HWQEnqLc70D
      l6oqovT035AjbElJtQUmnx9MPLtqShz5G23BAURU9TClCHUwMz3MU45qfyVk7v1T
      9IVWeZ3PY009yoxfp7Q7ULsMwJfkFkXJ8Zfx3H44U2+mOzya5QvVhkf6Ij17t1WN
      IghRCWv8bbwbhs9avgsr9Dvnk0qtuzdesfzwdRPe606B2tjhkpry68EAfGAcI35O
      fdq+LQ4q7lkPW+ilPh+SvZj9JhEFXtZWL+Nu582DxVbP83ubAgMBAAGjQjBAMA4G
      A1UdDwEB/wQEAwICBDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQRUcanyO1r
      qVfmT5vk5BA65xuDbjANBgkqhkiG9w0BAQsFAAOCAQEAXj0A/LA3JgDYeaCtSk8S
      MQOu/23x/DuHzQ8GRtJ3m9YqjWAEtUtLdm1b5lVC64SNhWYH7l0eSsJeKdYBYVCm
      sAYCvi+jXZ3P/L5sxxNtYV72d/R9xn+JyHB6GCD6/e5VP5WqT8pWlAJKmv/XGntI
      GYVg11U/Fst6PoUD6r7qqy0JiiAHoMiUc/LCTPtkknmaTdkA4w/WlPg2K5RnOg9Y
      uOELUsOcqa19JKZs1um4Ci7VdQfyOerTHwi/0cjUImxVOyn7nZZ1LPDUkB0GDPnO
      iCPkOWaErpqIB+kHI5Z6j8PPdm7a/C7DdLIDCBy4/BkNz1IjhmoVyDSefKMyL6r6
      /Q==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    creationTimestamp: "2026-06-09T14:18:57Z"
    labels:
      istio.io/config: "true"
    name: istio-ca-root-cert
    namespace: sample
    resourceVersion: "624"
    uid: a6bbd053-46e5-46a7-b330-00a7a28f1290
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIcFZkRvS10+kwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjA2MDkxNDEzMjFaFw0zNjA2MDYxNDE4MjFaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQDI0wh7NMK9k5J+TGZ8Q9NqrGz4F7dnnV6sRewd6RePvj+46rBhXhv6jUiH
      z9ijSbWzgTpHf7X29oyEWt+dajqS0b7/WNkoPGcoyIQmuRuIDGbiNf7Z6Wt+oRw3
      M9C7Pu49YD8OkAz+qH4qboCKWobY2Eyc/SB+EM7izsQqcdOjdLXZPjVkC4H5Qm0+
      fmQ0dXHdv7WVCaW5BLcevZKiOr3UoRZPbl29PJBzWdjm38rdOTBUwhAl+ER6h4t/
      CNLcZUeW5IMtDbQb/l368XEwn8oFeNHD1SS/NCblrDVBDj0hKMA8vuCqeGcs/pxq
      A1cqWAkVjzT9l3kzONTLbnrnGKdXAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRZ2LsXxmIB67muMFtipJnzmYDc/jAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQCbhob6AIjj
      5kPqY/Nfs9M39AHIaJbo09DY1qJXvL9VIqsBwdiHz4Z6Xk+bHX9ZCtV7sYcstRbj
      u1uQS4I+YJEncNlRfcWJf084fL7WcSqSgbrCR6CzFsXzJNoEPZlPON6Q8BjrOuQj
      pMsMuNL4qZddANAtg4bZe1YBZQzBjrB78c3XK86g9TrBJqCdjus0JU6ITKC4FD4y
      gy324nM0a+O9OPNDW//Vp1Bf9CxtgylWcMu9mJ0JhENxhp7s6SLGxKxk6mmsitzS
      3pezSQkfgWlzzjcboEn96WxPWmZzZsPSqGQvh3hWglrKIjshpFQRbUpwcutiuj1H
      2g5I5OLL/+qH
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-06-09T14:18:57Z"
    name: kube-root-ca.crt
    namespace: sample
    resourceVersion: "623"
    uid: 54ad517a-ee0e-4551-9903-d83469889dd4
kind: List
metadata:
  resourceVersion: ""
