"""``chart-test-swarm fix <rec-id>`` subcommand — LLM-driven fix workflow.

Reads the fix prompt file generated by the recommendations page, invokes
``CTS_LLM_CMD`` (same as ``generate author``) to produce a chart fix,
applies the suggestion, re-runs the scenario on kind, and updates the
recommendation status accordingly.

Flow:
  1. Read ``reports/fixes/<rec-id>/.fix-prompt.json``
  2. Resolve ``CTS_LLM_CMD`` (or discover ``droid`` on PATH)
  3. Invoke LLM with the fix prompt as stdin input
  4. Apply the LLM-suggested change to the chart
  5. Re-run the associated scenario on a kind cluster
  6. Update recommendation status: ``fixed`` if PASS, ``open`` if FAIL
  7. Append a history entry to ``reports/fixes/<rec-id>/history.json``
  8. Rebuild the dashboard

Error cases:
  - Exit non-zero if rec-id not found (no .fix-prompt.json)
  - Exit non-zero if CTS_LLM_CMD not set and ``droid`` not on PATH
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path
from shutil import which
from typing import Any, NoReturn

# ── Error helpers ───────────────────────────────────────────────────────────


def _die(msg: str, code: int = 1) -> NoReturn:
    """Print *msg* to stderr and exit with *code*."""
    print(msg, file=sys.stderr)
    raise SystemExit(code)


def _debug(msg: str) -> None:
    """Print a debug trace line to stderr when ``CTS_DEBUG`` is set."""
    if os.environ.get("CTS_DEBUG", "").strip() in ("1", "true", "yes"):
        print(f"[cts debug] {msg}", file=sys.stderr)


# ── Path resolution ─────────────────────────────────────────────────────────


def _resolve_engine_script(name: str) -> Path:
    """Return the absolute path to ``engine/scripts/<name>``.

    Resolution order:
      1. ``CTS_ENGINE_SCRIPTS_DIR`` env var (for testing with stubs)
      2. Walk up from this source file to the repo root
    """
    env_override = os.environ.get("CTS_ENGINE_SCRIPTS_DIR")
    if env_override:
        return Path(env_override) / name

    # Walk up from src/chart_test_swarm/commands/fix_cmd.py
    #   → chart_test_swarm/ → src/ → testgrid/ → engine/ → repo root
    this_file = Path(__file__).resolve()
    engine_dir = this_file.parents[3]  # commands → chart_test_swarm → src → testgrid
    root_dir = engine_dir.parents[1]  # testgrid → engine → root
    return root_dir / "engine" / "scripts" / name


def _resolve_project_dir(explicit: str | None) -> Path:
    """Return the absolute project directory.

    Precedence: *explicit* > ``PROJECT_DIR`` env > current working directory.
    """
    if explicit:
        return Path(explicit).resolve()
    if os.environ.get("PROJECT_DIR"):
        return Path(os.environ["PROJECT_DIR"]).resolve()
    return Path.cwd()


# ── LLM command resolution ──────────────────────────────────────────────────


def _resolve_llm_cmd() -> list[str]:
    """Resolve the LLM command to invoke.

    1. ``CTS_LLM_CMD`` env var (split on whitespace).
    2. Auto-discover ``droid`` on PATH via ``shutil.which``.

    Returns a list suitable for ``subprocess.run``.

    Raises ``SystemExit`` if no LLM binary is reachable.
    """
    cts_llm_cmd = os.environ.get("CTS_LLM_CMD", "").strip()
    if cts_llm_cmd:
        _debug(f"CTS_LLM_CMD resolved from env: {cts_llm_cmd}")
        return cts_llm_cmd.split()

    droid_path = which("droid")
    if droid_path:
        _debug(f"Auto-discovered droid at: {droid_path}")
        return [droid_path, "generate", "scenario"]

    # No LLM binary found — produce a clear actionable error.
    path_dirs = os.environ.get("PATH", "").split(os.pathsep)
    _die(
        "ERROR: No LLM binary found.\n\n"
        "  • CTS_LLM_CMD environment variable is not set.\n"
        "  • Searched PATH for: droid\n"
        f"  • PATH directories checked: {', '.join(path_dirs)}\n\n"
        "To fix this, set CTS_LLM_CMD to point at your droid/agent CLI:\n\n"
        '    export CTS_LLM_CMD="droid generate scenario"\n\n'
        "Or install the droid CLI from https://docs.factory.ai/cli",
        code=10,
    )


# ── Step 1: Read fix prompt ─────────────────────────────────────────────────


def load_fix_prompt(reports_dir: Path, rec_id: str) -> dict[str, str] | None:
    """Read ``reports/fixes/<rec-id>/.fix-prompt.json``.

    Returns the parsed JSON dict on success, or ``None`` when the file
    does not exist.
    """
    prompt_file = reports_dir / "fixes" / rec_id / ".fix-prompt.json"
    if not prompt_file.is_file():
        return None
    try:
        data: dict[str, str] = json.loads(prompt_file.read_text(encoding="utf-8"))
        return data
    except Exception:
        return None


# ── Step 2: Invoke LLM ─────────────────────────────────────────────────────


def call_llm(fix_prompt: str, *, timeout: int = 120) -> str:
    """Invoke ``CTS_LLM_CMD`` with *fix_prompt* as stdin; return stdout.

    Raises ``SystemExit`` if the subprocess fails (non-zero exit, not found,
    or timeout).
    """
    llm_cmd = _resolve_llm_cmd()
    _debug(f"Calling LLM: {' '.join(llm_cmd)}")

    prompt = (
        "You are a Helm chart fix agent. Apply the following fix to the chart.\n\n"
        f"{fix_prompt}\n\n"
        "Output ONLY the modified file content. For each file you change, "
        "start with a line like:\n"
        "CHANGED FILE: <relative-path-from-chart-root>\n"
        "Then output the full new content of that file.\n"
        "If no changes are needed, output: NO CHANGE\n"
    )

    try:
        result = subprocess.run(
            llm_cmd,
            input=prompt,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        _debug(f"LLM exit code: {result.returncode}")
        if result.stderr:
            _debug(f"LLM stderr: {result.stderr[:500]}")
    except subprocess.TimeoutExpired:
        _die(f"ERROR: LLM command timed out after {timeout}s.", code=11)
    except FileNotFoundError as exc:
        _die(
            f"ERROR: LLM command not found: {llm_cmd[0]}\n"
            f"  Details: {exc}\n"
            f"  Check that CTS_LLM_CMD is set correctly.",
            code=12,
        )

    if result.returncode != 0:
        _die(
            f"ERROR: LLM command exited with code {result.returncode}.\n"
            f"  stderr: {result.stderr[:500] if result.stderr else '(none)'}",
            code=13,
        )

    return result.stdout


# ── Step 3: Apply LLM suggestion to chart ───────────────────────────────────

_EXECUTABLE_BASENAME_SUFFIXES = {
    ".app",
    ".bat",
    ".bash",
    ".cmd",
    ".com",
    ".exe",
    ".fish",
    ".js",
    ".ksh",
    ".pl",
    ".ps1",
    ".py",
    ".rb",
    ".sh",
    ".zsh",
}
_DENIED_CHART_TEST_DIRS = {"asserts", "assertions"}
_ALLOWED_SUFFIXES = {".yaml", ".yml", ".tpl"}


def apply_llm_suggestion(chart_dir: Path, llm_output: str) -> str:
    """Apply the LLM-suggested change to the chart directory.

    Parses the LLM output for ``CHANGED FILE: <path>`` markers and writes
    the subsequent content to the corresponding file under *chart_dir*.

    Returns a git diff string of the changes (or empty string if git is
    unavailable or no changes were made).
    """
    changes_made = False
    lines = llm_output.splitlines()

    current_file: str | None = None
    current_lines: list[str] = []

    for line in lines:
        if line.startswith("CHANGED FILE: "):
            # Flush previous file
            if current_file is not None and current_lines:
                _write_chart_file(chart_dir, current_file, "\n".join(current_lines) + "\n")
                changes_made = True

            current_file = line[len("CHANGED FILE: ") :].strip()
            current_lines = []
        elif line.strip() == "NO CHANGE":
            pass  # No changes needed
        else:
            if current_file is not None:
                current_lines.append(line)

    # Flush last file
    if current_file is not None and current_lines:
        _write_chart_file(chart_dir, current_file, "\n".join(current_lines) + "\n")
        changes_made = True

    # Generate a diff if changes were made
    diff = ""
    if changes_made:
        diff = _git_diff(chart_dir)

    return diff


def _write_chart_file(chart_dir: Path, relative_path: str, content: str) -> None:
    """Write *content* to *chart_dir* / *relative_path*.

    Raises ``ValueError`` if the resolved target path escapes *chart_dir*
    (path traversal protection) or if the path is outside the non-executable
    chart template/values surface.
    """
    chart_root = chart_dir.resolve()
    target = (chart_root / relative_path).resolve()
    if not target.is_relative_to(chart_root):
        raise ValueError(
            f"Refusing to write {relative_path}: resolved path "
            f"{target} escapes chart directory {chart_root}"
        )
    _validate_chart_write_path(relative_path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    os.chmod(target, 0o644)
    _debug(f"Wrote chart file: {target}")


def _validate_chart_write_path(relative_path: str) -> None:
    """Validate that *relative_path* is an allowed non-executable chart file."""
    rel_path = Path(relative_path)
    parts = rel_path.parts
    if not parts:
        raise ValueError("Refusing to write empty chart path")

    if _is_under_denied_chart_test_dir(parts):
        raise ValueError(
            f"Refusing to write {relative_path}: writes into executable chart-test dir"
        )

    if _basename_looks_executable(rel_path.name):
        raise ValueError(f"Refusing to write {relative_path}: executable or script-like file type")

    if not _is_allowed_chart_surface(rel_path):
        raise ValueError(
            f"Refusing to write {relative_path}: outside allowed chart template/values surface"
        )


def _is_under_denied_chart_test_dir(parts: tuple[str, ...]) -> bool:
    """Return ``True`` for paths under chart-test/asserts or chart-test/assertions."""
    return len(parts) >= 2 and parts[0] == "chart-test" and parts[1] in _DENIED_CHART_TEST_DIRS


def _basename_looks_executable(name: str) -> bool:
    """Return ``True`` when the basename has a script/executable suffix."""
    suffix = Path(name).suffix.lower()
    if suffix in _EXECUTABLE_BASENAME_SUFFIXES:
        return True

    pathext = os.environ.get("PATHEXT", "")
    pathext_suffixes = {
        ext.lower()
        for pathsep_part in pathext.split(os.pathsep)
        for ext in pathsep_part.split(";")
        if ext
    }
    return suffix in pathext_suffixes


def _is_allowed_chart_surface(rel_path: Path) -> bool:
    """Return ``True`` when *rel_path* is in the chart metadata/template/values surface."""
    parts = rel_path.parts
    name = rel_path.name
    suffix = rel_path.suffix.lower()

    if suffix == ".tpl":
        return True

    if len(parts) == 1:
        if name == "Chart.yaml":
            return True
        return name.startswith("values") and suffix in _ALLOWED_SUFFIXES - {".tpl"}

    return parts[0] == "templates"


def _git_diff(chart_dir: Path) -> str:
    """Return a git diff for the chart directory, or empty string on error."""
    try:
        result = subprocess.run(
            ["git", "diff", str(chart_dir)],
            capture_output=True,
            text=True,
            timeout=10,
            cwd=chart_dir,
        )
        return result.stdout
    except Exception:
        return ""


# ── Step 4: Re-run scenario ────────────────────────────────────────────────


def rerun_scenario(
    *,
    scenario_path: str,
    reports_dir: str,
    project_dir: str | Path,
    timeout: int = 600,
) -> str:
    """Re-run a single scenario on a kind cluster and return its status.

    Invokes ``dispatch-swarm.sh`` (or ``run-scenario.sh``) with the
    scenario file.  Returns ``"PASS"`` or ``"FAIL"`` based on the
    subprocess exit code.
    """
    script = _resolve_engine_script("dispatch-swarm.sh")
    if not script.is_file():
        _die(f"ERROR: dispatch-swarm.sh not found at {script}", code=1)

    scenario_file = Path(scenario_path)
    if not scenario_file.is_file():
        _die(
            f"ERROR: scenario file not found: {scenario_path}",
            code=1,
        )

    resolved_project = Path(str(project_dir)).resolve()

    env = os.environ.copy()
    env["REPORTS_DIR"] = str(reports_dir)
    env["PROJECT_DIR"] = str(resolved_project)
    env["PROVIDER"] = "kind"
    env["CTS_SCENARIOS"] = str(scenario_file)

    _debug(f"Re-running scenario: {scenario_path}")
    _debug(f"Reports dir: {reports_dir}")
    _debug(f"Project dir: {resolved_project}")

    try:
        run_id = f"fix-run-{_timestamp_short()}"
        result = subprocess.run(
            ["bash", str(script), str(resolved_project), "single", "1", run_id],
            env=env,
            capture_output=True,
            text=True,
            timeout=timeout,
        )

        if result.stdout:
            sys.stdout.write(result.stdout)
            sys.stdout.flush()
        if result.stderr:
            sys.stderr.write(result.stderr)
            sys.stderr.flush()

        _debug(f"Scenario re-run exit code: {result.returncode}")

        # Determine status from exit code
        return "PASS" if result.returncode == 0 else "FAIL"
    except subprocess.TimeoutExpired:
        _die(f"ERROR: Scenario re-run timed out after {timeout}s.", code=14)
    except FileNotFoundError:
        _die(
            f"ERROR: dispatch-swarm.sh not found: {script}",
            code=15,
        )


def _timestamp_short() -> str:
    """Return a short timestamp string for run IDs: ``YYYYmmdd-HHMMSS``."""
    return datetime.now(UTC).strftime("%Y%m%d-%H%M%S")


# ── Scenario path resolution ────────────────────────────────────────────────


def _resolve_scenarios_dir(project_dir: Path) -> Path:
    """Return the path to the scenario catalog under the project directory.

    The default location is
    ``<project_dir>/chart-test/scenarios/``.  Override via
    ``CTS_SCENARIOS_DIR`` env var (for testing with stubs).
    """
    env_override = os.environ.get("CTS_SCENARIOS_DIR")
    if env_override:
        return Path(env_override)
    return project_dir / "chart-test" / "scenarios"


def resolve_scenario_path(scenario_id: str, scenarios_dir: Path) -> Path | None:
    """Resolve a ``scenario_id`` to an actual file path under *scenarios_dir*.

    Scans ``<scenarios_dir>/<category>/<scenario_id>.yaml`` for a file
    whose YAML ``id`` field matches *scenario_id*.  Returns the first
    matching ``Path`` or ``None`` if no match is found.
    """
    if not scenarios_dir.is_dir():
        return None

    for candidate in sorted(scenarios_dir.rglob("*.yaml")):
        if not candidate.is_file():
            continue
        # Fast path: filename matches scenario_id
        if candidate.stem == scenario_id:
            # Verify the id field matches (for correctness)
            try:
                import yaml

                with candidate.open(encoding="utf-8") as f:
                    doc = yaml.safe_load(f)
                if isinstance(doc, dict) and doc.get("id") == scenario_id:
                    return candidate
            except Exception:
                continue

    return None


# ── Step 5: Update recommendation status ────────────────────────────────────


def read_recommendations_json(reports_dir: Path) -> dict[str, Any]:
    """Read and parse ``reports/recommendations.json``.

    Returns the parsed JSON dict, or an empty dict on error.
    """
    rec_json = reports_dir / "recommendations.json"
    if not rec_json.is_file():
        return {}
    try:
        data: dict[str, Any] = json.loads(rec_json.read_text(encoding="utf-8"))
        return data
    except Exception:
        return {}


def update_recommendation_status(
    reports_dir: Path,
    rec_id: str,
    rerun_status: str,
) -> bool:
    """Update the recommendation status in recommendations.json.

    Sets the recommendation with *rec_id* to:
    - ``"fixed"`` if *rerun_status* is ``"PASS"``
    - ``"open"`` if *rerun_status* is ``"FAIL"``

    Also updates ``updated_at`` to the current UTC timestamp.

    Returns ``True`` if the recommendation was found and updated,
    ``False`` otherwise.
    """
    data = read_recommendations_json(reports_dir)
    recs = data.get("recommendations", [])

    found = False
    new_status = "fixed" if rerun_status == "PASS" else "open"
    now = datetime.now(UTC).isoformat()

    for rec in recs:
        if rec.get("id") == rec_id:
            rec["status"] = new_status
            rec["updated_at"] = now
            found = True
            break

    if not found:
        return False

    # Write back
    reports_dir.mkdir(parents=True, exist_ok=True)
    rec_json = reports_dir / "recommendations.json"
    rec_json.write_text(
        json.dumps(data, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    _debug(f"Updated recommendation {rec_id} status to {new_status}")
    return True


# ── Step 6: Append history entry ────────────────────────────────────────────


def append_history_entry(
    *,
    reports_dir: Path,
    rec_id: str,
    prompt_used: str,
    diff: str,
    re_run_status: str,
    result: str,
) -> None:
    """Append a fix attempt entry to ``reports/fixes/<rec-id>/history.json``.

    Creates the history file if it doesn't exist.  Each entry contains:
    - ``timestamp`` (ISO 8601 UTC)
    - ``action`` (always ``"fix_attempt"``)
    - ``prompt_used``
    - ``diff``
    - ``re_run_status``
    - ``result``
    """
    fix_dir = reports_dir / "fixes" / rec_id
    fix_dir.mkdir(parents=True, exist_ok=True)

    history_file = fix_dir / "history.json"
    existing: list[dict[str, str]] = []
    if history_file.is_file():
        try:
            existing = json.loads(history_file.read_text(encoding="utf-8"))
            if not isinstance(existing, list):
                existing = []
        except Exception:
            existing = []

    entry: dict[str, str] = {
        "timestamp": datetime.now(UTC).isoformat(),
        "action": "fix_attempt",
        "prompt_used": prompt_used,
        "diff": diff,
        "re_run_status": re_run_status,
        "result": result,
    }

    existing.append(entry)
    history_file.write_text(
        json.dumps(existing, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    _debug(f"Appended history entry for {rec_id}: {result}")


# ── Step 7: Rebuild dashboard ──────────────────────────────────────────────


def rebuild_dashboard(
    *,
    reports_dir: str,
    project_dir: str,
) -> None:
    """Rebuild the dashboard by invoking ``build-dashboard.sh``."""
    script = _resolve_engine_script("build-dashboard.sh")
    if not script.is_file():
        _debug("build-dashboard.sh not found; skipping dashboard rebuild")
        return

    env = os.environ.copy()
    env["REPORTS_DIR"] = reports_dir
    env["PROJECT_DIR"] = project_dir

    _debug("Rebuilding dashboard...")

    try:
        result = subprocess.run(
            ["bash", str(script)],
            env=env,
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.stdout:
            sys.stdout.write(result.stdout)
            sys.stdout.flush()
        if result.returncode != 0:
            _debug(f"Dashboard rebuild exited with code {result.returncode}; continuing anyway")
    except Exception as exc:
        _debug(f"Dashboard rebuild failed: {exc}; continuing anyway")


# ── Fix prompt file writer (used by recommendations page) ────────────────────


def write_fix_prompt_file(
    *,
    reports_dir: Path,
    rec_id: str,
    rec_data: dict[str, Any],
    scenario_path: str,
    chart_path: str,
) -> Path:
    """Write a ``.fix-prompt.json`` file for a recommendation.

    Creates ``reports/fixes/<rec-id>/.fix-prompt.json`` with the
    recommendation's fix prompt, scenario path, and chart path.

    Returns the path to the created file.
    """
    fix_dir = reports_dir / "fixes" / rec_id
    fix_dir.mkdir(parents=True, exist_ok=True)

    prompt_file = fix_dir / ".fix-prompt.json"
    data: dict[str, str] = {
        "recommendation_id": rec_id,
        "fix_prompt": str(rec_data.get("fix_prompt", "")),
        "scenario_path": scenario_path,
        "chart_path": chart_path,
        "created_at": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }

    prompt_file.write_text(
        json.dumps(data, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    _debug(f"Wrote fix prompt file: {prompt_file}")
    return prompt_file


# ── Context dataclass for fix workflow ───────────────────────────────────────


class FixContext:
    """Holds resolved paths and config for a single fix invocation.

    Attributes
    ----------
    rec_id:
        The recommendation ID being fixed.
    reports_dir:
        Path to the reports directory.
    project_dir:
        Path to the project directory.
    fix_prompt_data:
        Parsed contents of ``.fix-prompt.json``.
    chart_dir:
        Path to the chart directory (from fix_prompt_data).
    scenario_path:
        Path to the scenario YAML (from fix_prompt_data).
    """

    rec_id: str
    reports_dir: Path
    project_dir: Path
    fix_prompt_data: dict[str, str]
    chart_dir: Path
    scenario_path: str

    def __init__(
        self,
        rec_id: str,
        reports_dir: Path,
        project_dir: Path,
        fix_prompt_data: dict[str, str],
    ) -> None:
        self.rec_id = rec_id
        self.reports_dir = reports_dir
        self.project_dir = project_dir.resolve()
        self.fix_prompt_data = fix_prompt_data
        chart_rel = fix_prompt_data.get("chart_path", "chart")
        if os.path.isabs(chart_rel):
            _die(
                f"ERROR: chart_path must be relative, got absolute: {chart_rel}",
                code=23,
            )
        chart_dir = (self.project_dir / chart_rel).resolve()
        if not chart_dir.is_relative_to(self.project_dir):
            _die(
                f"ERROR: chart_path escapes project dir: {chart_rel}",
                code=23,
            )
        self.chart_dir = chart_dir
        self.scenario_path = fix_prompt_data.get("scenario_path", "")


# ── Main entry point ────────────────────────────────────────────────────────


def fix_cmd(
    *,
    rec_id: str,
    reports_dir: str | None = None,
    project_dir: str | None = None,
    timeout: int = 120,
    run_timeout: int = 600,
) -> None:
    """Execute the fix workflow for a recommendation.

    Core flow:
      1. Read ``reports/fixes/<rec-id>/.fix-prompt.json``
      2. Resolve scenario_id to file path via scenario catalog
      3. Invoke LLM with the fix prompt (validates CTS_LLM_CMD)
      4. Apply suggested change to chart
      5. Re-run scenario on kind
      6. Update recommendation status
      7. Append history entry
      8. Rebuild dashboard
    """
    # ── 1. Resolve reports and project dirs ──────────────────────────────
    resolved_reports = _resolve_reports_dir(reports_dir)
    resolved_project = _resolve_project_dir(project_dir)

    # ── 2. Read fix prompt ──────────────────────────────────────────────
    prompt_data = load_fix_prompt(resolved_reports, rec_id)
    if prompt_data is None:
        _die(
            f"ERROR: Fix prompt not found for rec-id '{rec_id}'.\n"
            f"  Expected: {resolved_reports / 'fixes' / rec_id / '.fix-prompt.json'}\n"
            f"  Click the FIX button on the recommendations page to create it.",
            code=20,
        )

    ctx = FixContext(
        rec_id=rec_id,
        reports_dir=resolved_reports,
        project_dir=resolved_project,
        fix_prompt_data=prompt_data,
    )

    _debug(f"Fix prompt loaded for {rec_id}")
    _debug(f"  Chart path: {ctx.chart_dir}")
    _debug(f"  Scenario path: {ctx.scenario_path}")

    # ── 3. Resolve scenario path (scenario_id → file path) ───────────
    # The .fix-prompt.json may contain either:
    #  (a) a full file path like "chart-test/scenarios/capability/labels-on.yaml"
    #  (b) a bare scenario_id like "labels-on" (when render.py writes
    #      rec.get("scenario_id", "") into scenario_path)
    # Try the path as-is first; if not found, resolve via scenario catalog.
    scenario_path = ctx.scenario_path
    scenario_file = Path(scenario_path)
    resolved_scenario_path: str | None = None

    if scenario_file.is_file():
        # Case (a): already a valid file path
        resolved_scenario_path = scenario_path
    else:
        # Try interpreting scenario_path relative to project_dir
        candidate = resolved_project / scenario_path
        if candidate.is_file():
            resolved_scenario_path = str(candidate)
        else:
            # Case (b): bare scenario_id — resolve via scenario catalog
            scenarios_dir = _resolve_scenarios_dir(resolved_project)
            resolved = resolve_scenario_path(scenario_path, scenarios_dir)
            if resolved is not None:
                resolved_scenario_path = str(resolved)
                _debug(f"Resolved scenario_id '{scenario_path}' → {resolved_scenario_path}")

    if resolved_scenario_path is None:
        _die(
            f"ERROR: Cannot resolve scenario '{scenario_path}' to a file.\n"
            f"  Tried as-is: {scenario_path}\n"
            f"  Tried relative to project: {resolved_project / scenario_path}\n"
            f"  Also searched scenario catalog under: {_resolve_scenarios_dir(resolved_project)}\n"
            f"  The scenario YAML must exist under chart-test/scenarios/<category>/<scenario>.yaml",
            code=22,
        )

    # ── 4. Invoke LLM (also validates CTS_LLM_CMD is set) ──────────────
    fix_prompt = prompt_data.get("fix_prompt", "")
    if not fix_prompt:
        _die(
            f"ERROR: Fix prompt is empty for rec-id '{rec_id}'.",
            code=21,
        )

    print(f"[fix] Invoking LLM for {rec_id}...")
    llm_output = call_llm(fix_prompt, timeout=timeout)
    _debug(f"LLM output length: {len(llm_output)} chars")

    # ── 5. Apply LLM suggestion ─────────────────────────────────────────
    print("[fix] Applying LLM suggestion to chart...")
    diff = apply_llm_suggestion(ctx.chart_dir, llm_output)
    if not diff:
        _debug("No diff produced (LLM may not have changed any files)")

    # ── 6. Re-run scenario ─────────────────────────────────────────────
    print(f"[fix] Re-running scenario: {resolved_scenario_path}")
    rerun_status = rerun_scenario(
        scenario_path=resolved_scenario_path,
        reports_dir=str(ctx.reports_dir),
        project_dir=str(ctx.project_dir),
        timeout=run_timeout,
    )
    _debug(f"Re-run status: {rerun_status}")

    # ── 7. Update recommendation status ─────────────────────────────────
    new_status = "fixed" if rerun_status == "PASS" else "open"
    result_str = new_status
    updated = update_recommendation_status(ctx.reports_dir, rec_id, rerun_status)
    if not updated:
        _debug(f"Warning: recommendation {rec_id} not found in recommendations.json")
    print(f"[fix] Recommendation {rec_id} → status: {new_status}")

    # ── 8. Append history entry ─────────────────────────────────────────
    append_history_entry(
        reports_dir=ctx.reports_dir,
        rec_id=rec_id,
        prompt_used=fix_prompt,
        diff=diff,
        re_run_status=rerun_status,
        result=result_str,
    )

    # ── 9. Rebuild dashboard ────────────────────────────────────────────
    print("[fix] Rebuilding dashboard...")
    rebuild_dashboard(
        reports_dir=str(ctx.reports_dir),
        project_dir=str(ctx.project_dir),
    )

    print(f"[fix] Done. {rec_id} → {new_status}")


def _resolve_reports_dir(explicit: str | None) -> Path:
    """Resolve the reports directory.

    Precedence: *explicit* > ``REPORTS_DIR`` env > ``<repo_root>/reports``.
    """
    if explicit:
        return Path(explicit).resolve()

    env_reports = os.environ.get("REPORTS_DIR")
    if env_reports:
        return Path(env_reports).resolve()

    # Default: repo root / reports
    this_file = Path(__file__).resolve()
    engine_dir = this_file.parents[3]  # commands → chart_test_swarm → src → testgrid
    root_dir = engine_dir.parents[1]  # testgrid → engine → root
    return root_dir / "reports"
