apiVersion: v1
items:
- apiVersion: v1
  data:
    release: SDRzSUFBQUFBQUFDLzVSV2IzT3FPaFAvS3BrOGI5VUdyRmFaT1MvRUhwV2UxbFpyUlhtOGN5YUVDTFFoWkVqUVlxZmYvVTZ3b3YwelBlY3laQVkyMmQzZmIzZXp5UXZrT0tIUWdoSW5nbEZZZ3pGZnA5QjZnZXM0aytwM1FBVkxDeHBBQzVySWJOZFJxMjUyWjBiTE1rM0xhRFk2NStjbU11dm8zRUlJMWlERC8xa2xvSkprc1ZCeHlxRUZIUzRWWmd5UVZLTlJHbzlVV09VU1dyQ3krMXFESk1LWjBpZ1RxbkNBRmRiZjc1alVSWllHT1ZHd0JqYzBrM3Z6cUdFMFBqdTlpWG1jWUFha3dqeW94eHlVMWtFdWFRQlVDb0kwWEtkcHNKZldGWldxTHJjNFMyQU5ZaEhQSytNYnM1U0lvOFJvb05LZEtvUUdob1ZnTWNHbDE5Y2FaQ2w1Z2hiUEdhdEJSUlBCc0tJU1d2K3ZpRlRDc3ozMWhITFZLSERDTklPU00xd3ViREZQNWdVeDJjWi9UTVBsd3Q2U29tdmVURVNHM2RiVGJXei85QmEyOUp0TWVXNEw5Uk9EQmNQQjAzSXhqVzdETkhTR3JjaDNIOXJPU0YwNC9kYTk1ejZ6NVdMTXJwOUtlYmhlb0Y5TzM1Wkw5NHI1bzV0MlArNkZUdCtPeUtqM3JRNXAybXk1UzdWdW9mMWpkeHlSWFJyU3BneXZtUmY1b3pralJhdWFtNWhkdytlVGc3OWRhYk01M1pCSGJhTVhPa01qQ29iamREWWN4Sjc3dkN1eDkvOE9pOU8za2VjYVczODRRTjZzc3ZjK0RudGJIM2p1aDQ3cGJXeGYwS0tYUHlSejZibURuWGZmdWwyNkJuTkdSdmN0SmpzeW5EK2UySHIwelJaYXVpejNGbGNuZVBWQW9aOE1sRGZiNSt2VWw5TzNoZThPdUo1emVNbkpYYnJQaHJlNHliRnJSSjc1a0pOa3Z2V2JZeEVNdXdXOXQ3dnJtU2l4elpPQkROejU3anBoYXVrRzdKcFBJNit3dSt0NzU5ZlJmaTkwUnZhRzhPa0hUT1ZRem5DODhmazB3bTZMRWFiWFRkck9aZmdSWStHNWc2ZHlUWE04SVVrM3J1SjZNdkJvaXNqUGdBV1hhVWdMZTd0Y1ROUGJ1TGU1N3R0YnYzbUZidVBlK1UzZjd2YkRIejlnRFNacG9PS3k3cXV1Z1dib3drSmR5K3cwakhZYnRZd3V1bmhySEsrMUw3YUpwTmttSnZRUGV5UjQvUGtMbXl6M0x0UHd3WndYUWNJZXZZbFEzbUlhZWNNQldwWmM3RnpuOTl1ODgvSFdjL2UxRW96WVZ1ZnNRMzN2dk1XVmlkMnh6a1dMREIrK3FlL0JsbHdlOUsrWVA1eEh4SHpJWjdwT2RJNG42YWU4WGQ4ZjRtaS96ejhmTThJOXNkUzFNdXdXUWY5TmY1ODd0RnhjY1c4eG5WUTU2S1YvaUgvVGJDQ3owelRQTzRaeGlQOC9OYmpCTE5jZDZ3WEdDUTZwL3Npb1NHV3MwcXlBRnVSaHpKOTErOE5oMlF6Tml6cG1JdVpVZDcrTWxzMnduK1pjUWN1b3diZmthU3NpMWMyOWc2ck8yV2U1VkRSejd1RHJhdzFLRXRFRUgxcm4vdStJSGlGazFNdDNocEJWdmg2c3dYWE1OTmE5empkY2pXN2pITFhiQm1wMk9sV3R3UVR6ZUUybGdoYXMxK3NyL2o5d24rWVpvUlo0ZjlxY2ZWMk1LMzQ4S1N5d01WYjhLZWFCQmU3M2ExYjhjSXhaS3c2QXJ1dUQ0UldYZ3BKU3JHTmhnU29VV2lRcG8wU2xXVGtQQUJiaXFBZUFEcU44bTZxWGZ4Ym9vUDAvQUFwbklWVjNsZlJ2ZVgwNGk5NVR3MExJc3lPL3kycnR0eFFCWU5pblRINUZvNkwvVmpEU0FzWVgxQk9zU0hSOWF1VlRPQTRVRGhxbmVQVEQzbXQvMGdlZ3dxSWZrbktGWTA2elU1WDZHek1zeEZFSVFMay9MTERhYnduclpDdXM0T202MDR3ZFRWYWU3ajZrVUQ4WnhVSE1xWlIzV2VyVEQ3cVJVbUpJbFFWZWdNQXFzc0JacmFvRDhMcmlwNWNqbzFZMlZDa3dlWGNmMUxlVzRuZENWWlRxSzUyVUdMNytHd0FBLy8rK1NOdmROZ29BQUE9PQ==
  kind: Secret
  metadata:
    creationTimestamp: "2026-05-29T19:22:13Z"
    labels:
      modifiedAt: "1780082537"
      name: sample
      owner: helm
      status: deployed
      version: "1"
    name: sh.helm.release.v1.sample.v1
    namespace: sample
    resourceVersion: "478"
    uid: 3fadd5ea-0838-4339-b74f-8a0d78284770
  type: helm.sh/release.v1
kind: List
metadata:
  resourceVersion: ""
