apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2026-06-09T13:33:40Z"
    name: grpc-backend
    namespace: sample
    resourceVersion: "619"
    uid: 511052a6-6b35-46d2-b4e5-28e0bb518259
  spec:
    clusterIP: 10.96.134.3
    clusterIPs:
    - 10.96.134.3
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: grpc
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      app: grpc-backend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: sample
      meta.helm.sh/release-namespace: sample
    creationTimestamp: "2026-06-09T13:33:40Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    name: sample
    namespace: sample
    resourceVersion: "634"
    uid: ecb75bed-8222-4696-acd6-3fb009dc4753
  spec:
    clusterIP: 10.96.114.235
    clusterIPs:
    - 10.96.114.235
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: sample
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
