apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: sample
      meta.helm.sh/release-namespace: sample
      metallb.io/ip-allocated-from-pool: chart-test-pool
    creationTimestamp: "2026-06-03T03:54:40Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    name: sample
    namespace: sample
    resourceVersion: "753"
    uid: bc91219c-fae4-4d60-b4ed-b1b28d2f0fcc
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.96.36.164
    clusterIPs:
    - 10.96.36.164
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 30126
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: sample
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 172.20.255.200
        ipMode: VIP
kind: List
metadata:
  resourceVersion: ""
