apiVersion: v1
items:
- apiVersion: v1
  data:
    release: SDRzSUFBQUFBQUFDLzVSV2IzT3FPaFAvS3BrOGI5VUdyRmFaT1MvRUhwV2UxbFpyUlhtOGN5YUVDTFFoWkVqUVlxZmYvVTZ3b3YwelBlY3laQVkyMmQzZmIzZXp5UXZrT0tIUWdoSW5nbEZZZ3pGZnA5QjZnZXM0aytwM1FBVkxDeHBBQzVySWJOZFJxMjUyWjhhNWRkNjFUTE54anN4TzU2S096aTJFWUEweS9KOVZBaXBKRmdzVnB4eGEwT0ZTWWNZQVNUVWFwZkZJaFZVdW9RVXJ1NjgxU0NLY0tZMHlvUW9IV0dIOS9ZNUpYV1Jwa0JNRmEzQkRNN2szanhwRzQ3UFRtNWpIQ1daQUtzeURlc3hCYVIza2tnWkFwU0JJdzNXYUJudHBYVkdwNm5LTHN3VFdJQmJ4dkRLK01VdUpPRXFNQmlyZHFVSm9ZRmdJRmhOY2VuMnRRWmFTSjJqeG5MRWFWRFFSRENzcW9mWC9pa2dsUE50VFR5aFhqUUluVERNb09jUGx3aGJ6WkY0UWsyMzh4elJjTHV3dEticm16VVJrMkcwOTNjYjJUMjloUzcvSmxPZTJVRDh4V0RBY1BDMFgwK2cyVEVObjJJcDg5Nkh0ak5TRjAyL2RlKzR6V3k3RzdQcXBsSWZyQmZybDlHMjVkSytZUDdwcDkrTmU2UFR0aUl4NjMrcVFwczJXdTFUckZ0by9kc2NSMmFVaGJjcndtbm1SUDVvelVyU3F1WW5aTlh3K09mamJsVGFiMHcxNTFEWjZvVE0wb21BNFRtZkRRZXk1ejdzU2UvL3ZzRGg5RzNtdXNmV0hBK1ROS252djQ3QzM5WUhuZnVpWTNzYjJCUzE2K1VNeWw1NDcySG4zcmR1bGF6Qm5aSFRmWXJJancvbmppYTFIMzJ5aHBjdHliM0YxZ2xjUEZQckpRSG16ZmI1T2ZUbDlXL2p1Z09zNWg1ZWMzS1g3YkhpTG14eTdSdVNaRHpsSjVsdS9PUmJCc0Z2UWU3dTdub2tTMnp3WnlNQ2Q3NjRUcHBadXdLNzVOUElLdTd1K2QzNGQ3ZmRDWjJSdkNKOSt3RlFPNVF6SEc1OVBJK3kyR0dGNjNhVHRYSVlmTVJhZU8zZ3ExelRIRTVKMDR5cXVKd09QcG9qOERGaHdtWWEwc0xmTHhUUzlqWHViNjc2OTladFg2RGJ1bmQvMDdXNC8vUEVEMW1DU0Jpb3U2NzdxR21pR0xpelV0Y3hPdzJpM1Vjdm9va1BqZUsxOXNVMGt6VFl4b1gvWUk4SGp6MS9ZWkxsM21ZWVA1cndJRXZib1RZVHlGdFBJR3c3UXN1Umk1enEvMythZGo3ZWV1NitWWU1TMk9tY2Y2bnZuTGE1TTdJNTFMbHBrK1BCTmZRKzI1UEtnZjhYODRUd2k1a00rMDNXaWN6eEpQK1h0K3Y0UVIvdDkvdm1ZRWU2SnBhNlZZYmNJK20vNis5eWg1ZUtLZTR2cHBNcEJMLzFEL0p0bUE1bWRwbm5lTVl4RC9QK3B3UTFtdWU1WUx6Qk9jRWoxUjBaRkttT1ZaZ1cwSUE5ai9xemJIdzdMWm1oZTFERVRNYWU2KzJXMGJJYjlOT2NLV2tZTnZpVlBXeEdwYnU0ZFZIWE9Qc3Vsb3BsekIxOWZhMUNTaUNiNDBEcjNmMGYwQ0NHalhyNHpoS3p5OVdBTnJtT21zZTUxdnVGcWRCdm5xTjAyVUxQVHFXb05KcGpIYXlvVnRHQzlYbC94LzRIN05NOEl0Y0Q3MCticzYySmM4ZU5KWVlHTnNlSlBNUThzY0w5ZnMrS0hZOHhhY1FCMFhSOE1yN2dVbEpSaUhRc0xWS0hRSWtrWkpTck55bmtBc0JCSFBRQjBHT1hiVkwzOHMwQUg3ZjhCVURnTHFicXJwSC9MNjhOWjlKNGFGa0tlSGZsZFZtdS9wUWdBd3o1bDhpc2FGZjIzZ3BFV01MNmdubUJGb3V0VEs1L0NjYUJ3MERqRm94LzJYdnVUUGdBVkZ2MlFsQ3NjYzVxZHF0VGZtR0VoamtJQXl2MWhnZFYrUzFnblcyRUZUOWVkWnV4b3N2SjA5eUdGK3Nrb0RtSk9wYnpMVXA5KzBJMlVFa09xTFBBQ0JGYVJCYzVxVlIyQTF4VS92UndadGJLaFNvSEp1L3VndnJVVXZ4T3FvbFJmNmFURThQWGZBQUFBLy8rZi9CY2lOZ29BQUE9PQ==
  kind: Secret
  metadata:
    creationTimestamp: "2026-05-29T18:49:22Z"
    labels:
      modifiedAt: "1780080565"
      name: sample
      owner: helm
      status: deployed
      version: "1"
    name: sh.helm.release.v1.sample.v1
    namespace: sample
    resourceVersion: "469"
    uid: 1a61cfa9-138d-45dc-9fab-d2619c5ed1e4
  type: helm.sh/release.v1
kind: List
metadata:
  resourceVersion: ""
