apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIJgLuc60X5GEwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjA2MDkxMjU0NTNaFw0zNjA2MDYxMjU5NTNaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQC/gbdzNza9CFLNqxSDI+1J2+H7V7kZxtNfiu4olwviO7dLQ4nMQf2aujS8
      C63Ql8ltuf01IgApTMvtFxoyYOQAleVUIdsCrLDKp+jLbEBqfmeTOu4fmJWwAfwq
      86MBHRmHi4VPfkSVeqzBFgrqH0NKDcTPOi2VIMGZHziE4Z8EZriBLeyGGkuLpO4S
      V8LwRy9MDBqWK4L7lGkC93KZ2CSyETnNb1xl46ltVdOyUG9H39MNtUR/2D+dAd7c
      aAvbLprE1AlZWEwt7ZS7NGGoFFcGQSBuWphPxIfYI0Hb5Jf6yxhW1owCLPTinIVG
      VHtsnRH8feYDnYFijfNlWeXFgkQ9AgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTSbgaiTecLZaM6s+WzFp6GGA5aMzAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQCXURk8aqkq
      OLoTG+WRml6WqjwhLexSfI9m8s+ytXWNdUFvUfzvThxCZu9XX30WCKqEVfcpJGCB
      W4lSUpry3Gi4vdrNQIk30qw/MCW3L071wW7kdUaQuO22diYGSxEeSP69xYRKFAvV
      Nh8NiJv/vv7Vv5D03kel8mHj65NZGC/zHIbqtJNWVxkxaamSOuPCZRPGswmRZQj2
      r1xjmK61oZjp2Kj2oJ807q+DT6uoOqHjohC/wdYuqtis4Secvrn5xyMzb+MgV/PH
      /mB7l4OsdPRaytBXEz9N7dbTZu/pvy8TceM3kcLxggK3+WlHJa2aTzLuhFFt5hsL
      CJHbvqOFhLhN
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-06-09T13:00:18Z"
    name: kube-root-ca.crt
    namespace: sample
    resourceVersion: "461"
    uid: 3e390d5e-8372-45c0-9c6b-3d6992a05fd4
kind: List
metadata:
  resourceVersion: ""
