apiVersion: v1
items:
- apiVersion: v1
  data:
    release: SDRzSUFBQUFBQUFDLzVSV2JXL2l1aEwrSzVidlY2Qk9XR2lKZEQ0UXVrQzZMVjBvSlpETDFaSGptTVN0WTBleEF4dFcvZTlYRGlYUUYvWHNpV0lwR1h0bW5tZG1QUFp2S0hCS29RTVZUak5PWVFNeXNaSFErUTAzTEZmNjc0aG1YSlkwZ2c2MGtkMXRvazdUN3MydGptTjNIS3ZUNnJZUmFqZlJOd2NoMklBYy8xdU5pQ3FTczB3ekthQURQYUUwNWh3UWFiQm9nMFpwckFzRkhWaWJmV2xBa3VCY0c0d3AxVGpDR3B2dk56eWFXUzZqZ21qWWdGdWFxNE41MUxKYUg1M2VNY0ZTeklIU1dFUk5Ka0JsSFJTS1JrQkxFTWw0STJWMGtEWTFWYnFwZGpoUFlRUGlqQzFxNDF1N2ttUW5pZFZDbFR0ZFpnWVl6akxPQ0s2OHZqUWdsK1FaT3FMZ3ZBRTFUVE9PTlZYUStXOU5wQlplSEtpblZPaFdpVk51R0ZTYzRXcnBab3QwVVJLYmI4TW5HYStXN282VVBmdHVtdVhZN3p6Zk0vZDdzSFJWMk9ZNjhEdG9rRm84R2cyZlY4dFpjaC9MMkJ0MWt0Qi83SHBqZmVrTk9nK0IvNHV2bGhOKysxeko0ODBTL2ZBR3JscjVOendjMzNVSHJCOTdBemNoNC82WE9xVHQ4dFZlR3QzUytNZitKQ0Y3R2RPMmltOTVrSVRqQlNkbHA1NmIyajByRk5PanYzMWxzejNia2lkam94OTdJeXVKUmhNNUh3MVo0UC9hVjlnSGY0YkZHN2dvOEsxZE9CcWlZRjdiZXh1SGc2MTNQQS9EeFBTZXVaZTA3QmVQNlVJRi9uQWZQSFR1Vjc3RnZiSFZlNDNKbm93V1QyZTJua0s3ZzFZK0w0TGx6UmxlTTFBY3BrTWR6QS81T3ZmbERkd3M5SWZDekhtaTR1U3YvRjlXc0x3cnNHOGxnZjFZa0hTeEM5dVRMQnIxU3ZyZzlqYnpyTUsyU0ljcThoZjcyNVRybFIveFd6RkxndEx0YlI2OEh5ZjcvZGdidTFzaVp1OHdWVU43bzhrMkZMTUUreDFPdUZrMzdYclg4WHVNWmVBUG42czE3Y21VcEQxV3gvVnM0UEVNa2U4Umo2NWxURXQzdDFyTzVEM3JiMjhIN2k1czM2QjcxdjkyTjNCN2cvaXZ2MkFEcGpMU3JLcjd1bW1nT2JwMFVNK3hyMXBXdDRzNlZnOWR2amFPbDhZbjIwVFJmTXNJL1ljOUVqMTkvNEZ0WGdUWE1uNjBGMldVOHFkZ211bGdPVXVDMFJDdEtpNXVZZkw3WmQ3RlpCZjRoMXFKeG54bmN2YXV2dmZCOHNiRy9zVGtva05HajEvVTkzQkhyby82Tnp3Y0xSSmlQeFp6VXljbXgxUDVJVyszRDhjNHVtL3pMeWFjaUNCYm1Wb1o5Y3BvOEtwL3lCMWFMVzlFc0p4TjZ4ejA1VC9FdjIyM2tIM1Z0cjlkV2RZeC92OXJ3QzNtaGVsWXZ5RkxjVXpOUjA0enFaaVdlUWtkS0dJbWZwbjJoK09xR2RxWFRjd3pKcWpwZmptdG11RkFGa0pEeDJyQTErUVpLNWswemYwSzFaMXp3QXVsYWU3OWhDOHZEYWhJUWxOOGJKMkh2eE42aEpEVnJONDVRazcxQnJBQk40d2JyQWVkTDdoYXZkWTMxTzFhcUgxMVZkY2FKRkpzV0h6QUZ2V0ZrTHBxNHhWNXhTSktjTjVpU2pQWll2S0NpU2RLTkhSMFhsQ0ROOFdDYmFqUzBJSE5abk10L2dNZVpKRVQ2b0MzUjlYRjU1VzhGcWRqeGdGYmF5MmVtWWdjOEhCWXN4YkhNOUJaQ3dETXBqZ2FYZ3VWVVZLSlRTQWRVTWZSaUJUbGxHaVpWL01BNEN3NzZRRmdjcUJlcDVyVm53T3UwT0VmQUkzem1PcWZ0ZlJQZWIwN3lONVN3MW1tTGs3OHJ1dTFYMUlFZ09PUWN2VVpqWnIrYTdVcEIxaWZVRSt4SnNudHVaVVA0VGhTT0dxYzR6RVBmNnY5UVIrQUdvdDVpQlFhTTBIemM1WG1Lek9jWlNjaEFOWG1jc0Q2c0orY3MzMjBodWZyempOMk1sbDcrdmt1aGViSktZNllvRXI5ekdWSTMra21XbWNqcWgzd0cyUllKdzY0YU5SMUFGN1c0dnhtWlRXcWJxd3lUTjVjSmMyVnAvdzdwVHFSNWpxb0ZJWXYvdzhBQVAvL3pJVjJ3WEVLQUFBPQ==
  kind: Secret
  metadata:
    creationTimestamp: "2026-05-29T19:25:15Z"
    labels:
      modifiedAt: "1780082718"
      name: sample
      owner: helm
      status: deployed
      version: "1"
    name: sh.helm.release.v1.sample.v1
    namespace: sample
    resourceVersion: "853"
    uid: 8ee173b6-3adb-49ec-8c99-e90d27e573fe
  type: helm.sh/release.v1
kind: List
metadata:
  resourceVersion: ""
