#!/usr/bin/env bash
# regen.sh — Regenerate all TLS fixture material for chart-test-swarm certificates.
#
# This script regenerates the shared CA cert/key and all per-variant leaf
# certificates and Secret manifests under fixtures/certificates/.
# All generated material is test-only — NEVER use in production.
#
# Usage: ./regen.sh
# Prerequisites: openssl, yq
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "==> Regenerating shared CA…"
openssl genrsa -out ca.key 2048
openssl req -new -x509 -days 365 -key ca.key -out ca.crt \
  -subj "/C=US/ST=CA/O=Chart Test Swarm/CN=chart-test-swarm-ca" \
  -addext "basicConstraints=critical,CA:TRUE" \
  -addext "keyUsage=critical,keyCertSign,cRLSign"

# Add test-only header comment to ca.key
{
  echo '# test-only ephemeral key — regenerated by ./regen.sh; never used in production'
  echo '# Chart Test Swarm — certificates fixture set (F3.4)'
  cat ca.key
} > ca.key.tmp && mv ca.key.tmp ca.key

echo "  CA generated: ca.crt ($(wc -c < ca.crt) bytes), ca.key ($(wc -c < ca.key) bytes)"

# ---- manual-tls subdir ----
echo ""
echo "==> Regenerating manual-tls fixtures…"
MANUAL_DIR="$SCRIPT_DIR/manual-tls"
mkdir -p "$MANUAL_DIR"

# RSA CA for manual-tls
openssl genrsa -out "$MANUAL_DIR/ca.key" 2048
openssl req -new -x509 -days 365 -key "$MANUAL_DIR/ca.key" -out "$MANUAL_DIR/ca.crt" \
  -subj "/C=US/ST=CA/O=Chart Test Swarm/CN=chart-test-swarm-manual-tls-ca" \
  -addext "basicConstraints=critical,CA:TRUE" \
  -addext "keyUsage=critical,keyCertSign,cRLSign"

# Add header comment
{
  echo '# test-only ephemeral key — regenerated by ./regen.sh; never used in production'
  cat "$MANUAL_DIR/ca.key"
} > "$MANUAL_DIR/ca.key.tmp" && mv "$MANUAL_DIR/ca.key.tmp" "$MANUAL_DIR/ca.key"

# Basic RSA leaf cert
openssl genrsa -out "$MANUAL_DIR/basic-cert.key" 2048
openssl req -new -key "$MANUAL_DIR/basic-cert.key" -out "$MANUAL_DIR/basic-cert.csr" \
  -subj "/C=US/ST=CA/O=Chart Test Swarm/CN=chart-test-swarm-basic" \
  -addext "subjectAltName=DNS:sample.sample.svc"
openssl x509 -req -days 365 -in "$MANUAL_DIR/basic-cert.csr" \
  -CA "$MANUAL_DIR/ca.crt" -CAkey "$MANUAL_DIR/ca.key" -CAcreateserial \
  -out "$MANUAL_DIR/basic-cert.crt" \
  -copy_extensions copy 2>/dev/null || \
  openssl x509 -req -days 365 -in "$MANUAL_DIR/basic-cert.csr" \
    -CA "$MANUAL_DIR/ca.crt" -CAkey "$MANUAL_DIR/ca.key" -CAcreateserial \
    -out "$MANUAL_DIR/basic-cert.crt" \
    -extfile <(printf "subjectAltName=DNS:sample.sample.svc")
rm -f "$MANUAL_DIR/basic-cert.csr"

{ echo '# test-only ephemeral key — regenerated by ./regen.sh; never used in production'; cat "$MANUAL_DIR/basic-cert.key"; } > "$MANUAL_DIR/basic-cert.key.tmp" && mv "$MANUAL_DIR/basic-cert.key.tmp" "$MANUAL_DIR/basic-cert.key"

# Build the basic Secret manifest
CRT_B64=$(base64 < "$MANUAL_DIR/basic-cert.crt" | tr -d '\n')
KEY_B64=$(base64 < "$MANUAL_DIR/basic-cert.key" | tr -d '\n')
cat > "$MANUAL_DIR/manual-tls-basic-secret.yaml" << EOF
apiVersion: v1
data:
  tls.crt: $CRT_B64
  tls.key: $KEY_B64
kind: Secret
metadata:
  name: manual-tls-basic
  namespace: sample
type: kubernetes.io/tls
EOF
echo "  manual-tls-basic-secret.yaml regenerated"

# Multisite leaf cert (3 SANs)
openssl genrsa -out "$MANUAL_DIR/multisite-cert.key" 2048
openssl req -new -key "$MANUAL_DIR/multisite-cert.key" -out "$MANUAL_DIR/multisite-cert.csr" \
  -subj "/C=US/ST=CA/O=Chart Test Swarm/CN=chart-test-swarm-multisite" \
  -addext "subjectAltName=DNS:sample.sample.svc,DNS:api.sample.sample.svc,DNS:admin.sample.sample.svc"
openssl x509 -req -days 365 -in "$MANUAL_DIR/multisite-cert.csr" \
  -CA "$MANUAL_DIR/ca.crt" -CAkey "$MANUAL_DIR/ca.key" -CAcreateserial \
  -out "$MANUAL_DIR/multisite-cert.crt" \
  -extfile <(printf "subjectAltName=DNS:sample.sample.svc,DNS:api.sample.sample.svc,DNS:admin.sample.sample.svc")
rm -f "$MANUAL_DIR/multisite-cert.csr"

{ echo '# test-only ephemeral key — regenerated by ./regen.sh; never used in production'; cat "$MANUAL_DIR/multisite-cert.key"; } > "$MANUAL_DIR/multisite-cert.key.tmp" && mv "$MANUAL_DIR/multisite-cert.key.tmp" "$MANUAL_DIR/multisite-cert.key"

CRT_B64=$(base64 < "$MANUAL_DIR/multisite-cert.crt" | tr -d '\n')
KEY_B64=$(base64 < "$MANUAL_DIR/multisite-cert.key" | tr -d '\n')
cat > "$MANUAL_DIR/manual-tls-multisite-secret.yaml" << EOF
apiVersion: v1
data:
  tls.crt: $CRT_B64
  tls.key: $KEY_B64
kind: Secret
metadata:
  name: manual-tls-multisite
  namespace: sample
type: kubernetes.io/tls
EOF
echo "  manual-tls-multisite-secret.yaml regenerated"

# ECDSA leaf cert
openssl ecparam -genkey -name prime256v1 -out "$MANUAL_DIR/ecdsa-cert.key"
openssl ecparam -genkey -name prime256v1 -out "$MANUAL_DIR/ecdsa-ca.key"
openssl req -new -x509 -days 365 -key "$MANUAL_DIR/ecdsa-ca.key" -out "$MANUAL_DIR/ecdsa-ca.crt" \
  -subj "/C=US/ST=CA/O=Chart Test Swarm/CN=chart-test-swarm-ecdsa-ca" \
  -addext "basicConstraints=critical,CA:TRUE" \
  -addext "keyUsage=critical,keyCertSign,cRLSign"
openssl req -new -key "$MANUAL_DIR/ecdsa-cert.key" -out "$MANUAL_DIR/ecdsa-cert.csr" \
  -subj "/C=US/ST=CA/O=Chart Test Swarm/CN=chart-test-swarm-ecdsa" \
  -addext "subjectAltName=DNS:sample.sample.svc"
openssl x509 -req -days 365 -in "$MANUAL_DIR/ecdsa-cert.csr" \
  -CA "$MANUAL_DIR/ecdsa-ca.crt" -CAkey "$MANUAL_DIR/ecdsa-ca.key" -CAcreateserial \
  -out "$MANUAL_DIR/ecdsa-cert.crt" \
  -extfile <(printf "subjectAltName=DNS:sample.sample.svc")
rm -f "$MANUAL_DIR/ecdsa-cert.csr"

for k in ecdsa-ca.key ecdsa-cert.key; do
  { echo '# test-only ephemeral key — regenerated by ./regen.sh; never used in production'; cat "$MANUAL_DIR/$k"; } > "$MANUAL_DIR/$k.tmp" && mv "$MANUAL_DIR/$k.tmp" "$MANUAL_DIR/$k"
done

CRT_B64=$(base64 < "$MANUAL_DIR/ecdsa-cert.crt" | tr -d '\n')
KEY_B64=$(base64 < "$MANUAL_DIR/ecdsa-cert.key" | tr -d '\n')
cat > "$MANUAL_DIR/manual-tls-ecdsa-secret.yaml" << EOF
apiVersion: v1
data:
  tls.crt: $CRT_B64
  tls.key: $KEY_B64
kind: Secret
metadata:
  name: manual-tls-ecdsa
  namespace: sample
type: kubernetes.io/tls
EOF
echo "  manual-tls-ecdsa-secret.yaml regenerated"

echo ""
echo "==> All fixtures regenerated."
echo "    CA:      ca.crt / ca.key"
echo "    Subdirs: manual-tls/"
echo ""
echo "    Next: run 'helm lint examples/sample-product-chart/chart' and"
echo "          'bash engine/scripts/sweep-scenarios.sh' to verify."
