apiVersion: v1
items:
- apiVersion: v1
  data:
    release: SDRzSUFBQUFBQUFDLzVSV2IzT3FPaFAvS3BrOGI5VUdyRmFaT1MvRUhwV2UxbFpyUlhtOGN5YUVDTFFoWkVqUVlxZmYvVTZ3b3YwelBlY3laQVkyMmQzZmIzZXp5UXZrT0tIUWdoSW5nbEZZZ3pGZnA5QjZnZXM0aytwM1FBVkxDeHBBQzVySWJOZFJxMjUyWjBiYmFwbFc2NkxSTWMxT3ExVkg1eFpDc0FZWi9zOHFBWlVraTRXS1V3NHQ2SENwTUdPQXBCcU4wbmlrd2lxWDBJS1YzZGNhSkJIT2xFYVpVSVVEckxEK2ZzZWtMckkweUltQ05iaWhtZHliUncyajhkbnBUY3pqQkRNZ0ZlWkJQZWFndEE1eVNRT2dVaENrNFRwTmc3MjBycWhVZGJuRldRSnJFSXQ0WGhuZm1LVkVIQ1ZHQTVYdVZDRTBNQ3dFaXdrdXZiN1dJRXZKRTdSNHpsZ05LcG9JaGhXVjBQcC9SYVFTbnUycEo1U3JSb0VUcGhtVW5PRnlZWXQ1TWkrSXlUYitZeG91Ri9hV0ZGM3paaUl5N0xhZWJtUDdwN2V3cGQ5a3luTmJxSjhZTEJnT25wYUxhWFFicHFFemJFVysrOUIyUnVyQzZiZnVQZmVaTFJkamR2MVV5c1AxQXYxeStyWmN1bGZNSDkyMCszRXZkUHAyUkVhOWIzVkkwMmJMWGFwMUMrMGZ1K09JN05LUU5tVjR6YnpJSDgwWktWclYzTVRzR2o2ZkhQenRTcHZONllZOGFodTkwQmthVVRBY3A3UGhJUGJjNTEySnZmOTNXSnkralR6WDJQckRBZkptbGIzM2NkamIrc0J6UDNSTWIyUDdnaGE5L0NHWlM4OGQ3THo3MXUzU05aZ3pNcnB2TWRtUjRmenh4TmFqYjdiUTBtVzV0N2c2d2FzSEN2MWtvTHpaUGwrbnZweStMWHgzd1BXY3cwdE83dEo5TnJ6RlRZNWRJL0xNaDV3azg2M2ZISXRnMkMzb3ZkMWR6MFNKYlo0TVpPRE9kOWNKVTBzM1lOZDhHbm1GM1YzZk83K085bnVoTTdJM2hFOC9ZQ3FIY29iampjK25FWFpiakRDOWJ0SjJMc09QR0F2UEhUeVZhNXJqQ1VtNmNSWFhrNEZIVTBSK0JpeTRURU5hMk52bFlwcmV4cjNOZGQvZStzMHJkQnYzem0vNmRyY2YvdmdCYXpCSkF4V1hkVjkxRFRSREZ4YnFXbWFuWWJUYnFHVjAwY1ZiNDNpdGZiRk5KTTAyTWFGLzJDUEI0ODlmMkdTNWQ1bUdEK2E4Q0JMMjZFMkU4aGJUeUJzTzBMTGtZdWM2djkvbW5ZKzNucnV2bFdERXRqcG5IK3A3NXkydVRPeU9kUzVhWlBqd1RYMFB0dVR5b0gvRi9PRThJdVpEUHROMW9uTThTVC9sN2ZyK0VFZjdmZjc1bUJIdWlhV3VsV0czQ1Bwdit2dmNvZVhpaW51TDZhVEtRUy85US95YlpnT1puYVo1M2pHTVEvei9xY0VOWnJudVdDOHdUbkJJOVVkR1JTcGpsV1lGdENBUFkvNnMyeDhPeTJab1h0UXhFekdudXZ0bHRHeUcvVFRuQ2xwR0RiNGxUMXNScVc3dUhWUjF6ajdMcGFLWmN3ZGZYMnRRa29nbStOQTY5MzlIOUFnaG8xNitNNFNzOHZWZ0RhNWpwckh1ZGI3aGFuUWI1NmpkTmxDejA2bHFEU2FZeDJzcUZiUmd2VjVmOGYrQit6VFBDTFhBKzlQbTdPdGlYUEhqU1dHQmpiSGlUekVQTEhDL1g3UGloMlBNV25FQWRGMGZESys0RkpTVVloMExDMVNoMENKSkdTVXF6Y3A1QUxBUVJ6MEFkQmpsMjFTOS9MTkFCKzMvQVZBNEM2bTZxNlIveSt2RFdmU2VHaFpDbmgzNVhWWnJ2NlVJQU1NK1pmSXJHaFg5dDRLUkZqQytvSjVnUmFMclV5dWZ3bkdnY05BNHhhTWY5bDc3a3o0QUZSYjlrSlFySEhPYW5hclUzNWhoSVk1Q0FNcjlZWUhWZmt0WUoxdGhCVS9Ybldic2FMTHlkUGNoaGZySktBNWlUcVc4eTFLZmZ0Q05sQkpEcWl6d0FnUldrUVhPYWxVZGdOY1ZQNzBjR2JXeW9VcUJ5YnY3b0w2MUZMOFRxcUpVWCtta3hQRDEzd0FBQVAvL1pNY0JWVFlLQUFBPQ==
  kind: Secret
  metadata:
    creationTimestamp: "2026-05-29T20:52:57Z"
    labels:
      modifiedAt: "1780087980"
      name: sample
      owner: helm
      status: deployed
      version: "1"
    name: sh.helm.release.v1.sample.v1
    namespace: sample
    resourceVersion: "691"
    uid: 89a1a9ea-52c9-432d-bc9d-2e5175651ac7
  type: helm.sh/release.v1
kind: List
metadata:
  resourceVersion: ""
