apiVersion: v1
kind: Namespace
metadata:
  annotations:
    linkerd.io/inject: enabled
  creationTimestamp: "2026-06-02T17:39:00Z"
  labels:
    kubernetes.io/metadata.name: sample
    name: sample
  name: sample
  resourceVersion: "755"
  uid: 0a201899-93f6-483f-8960-43d964f06f84
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
