apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIQFL44AhCakEwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjA2MDkxMjU2MjdaFw0zNjA2MDYxMzAxMjdaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQC9ZFVezvwSZXlIZwppWg/JQW1eAHjyWswRiyANWUQ8xxqbuRnX7M2nM+3J
      ZucADiU+FtE3czSa+0HcKeP+lEHeT9WByLLTVeV5JyTPb/hKRrW8reIM6klg0aeu
      cQXiPyA46BZCCh/eWJEulXbOnZ8L08dft9VgLh6H+9lY65hdR2ycpY7muCqzaVEk
      mBBDA/+PRX95Iwgqb67Zxhl1iFyHtKQEqLS4n2UHM3aeomOpIJ9E8y5BB3v+4A0x
      GBDC2GkH0+wdDggChgFsQNJHbrBxQzeLjpswVQSV96m4P1dSmGXO6QojnHHsvDJr
      3bNhsRfpM7ZDjJs/gYzlN9SOTQNNAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSDjBr3kPLmcwTaRGwqKBwP54ZXKTAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQAbWo3xmmse
      1o3DcKlWGo1yNo8WFt6vcriLfUgfucTmLaOX4YuKRx6A4ECRreOx+LRWJOKTOcl5
      ysDo4m7S8KZE8Ac80AUNf7Bmfo9oLDtPwLn0XFfWKvcXRJsR6aHInaoFsIQUhF7k
      k95d94eC5ROuOPXDCs56Jg97Jsxsgr8akAJJQ6I8QyFOowrk4U0BmuDed8OQhYbr
      RmONTsHcAseTzg3YU4XZbja0/MgcX3c3vzuCd7zmR1ekuRYj7mjmhdfD9kYgthVd
      sIS0ERgvR1GXB2T4KyHnuHWIPg9czabKjTvwwWJ1mWBSrp84PbIUOrQYbmNHUaIo
      QHUW5msdgp09
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-06-09T13:01:53Z"
    name: kube-root-ca.crt
    namespace: sample
    resourceVersion: "403"
    uid: fdcf648c-67ee-45d7-bc1a-83e659dd6565
kind: List
metadata:
  resourceVersion: ""
