apiVersion: v1
items:
- apiVersion: v1
  data:
    root-cert.pem: |
      -----BEGIN CERTIFICATE-----
      MIIC/DCCAeSgAwIBAgIQT2uSoUlTb4yztca4EkNTOTANBgkqhkiG9w0BAQsFADAY
      MRYwFAYDVQQKEw1jbHVzdGVyLmxvY2FsMB4XDTI2MDYwOTE0MTY1MVoXDTM2MDYw
      NjE0MTY1MVowGDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcN
      AQEBBQADggEPADCCAQoCggEBALaCTa1ITFl7+ZtfysAIy9WwzTSci1CYQJIPiFVW
      eJrndMnQ2heUZcDPi2/Tjw6N10SPF5YtuB6UH7imfQnV6QMryrnvfM7gz+HcRTqz
      zaWAf1YlJGQ9+SLx7yas6K6d0NJsGBbRbgmgVCuRGmFCamci1n8zWYP8nGAoOvJ1
      nNi7w5haMOPSzxSYsbpL57NP5cbQWunp8pcm+CN6e21tCJnAPrrrBsZWMbQbPK8q
      YfEi4sK1DXYipBNhE/Kooe8ScFv1d48paXRTxOEF1lCCjEQ0ZCfUS5/eSYXOMkKX
      NIhLVc5LTv/4AhJ0+XaY0YzUG8zDUznZ4CZpJtQ1DK7bobcCAwEAAaNCMEAwDgYD
      VR0PAQH/BAQDAgIEMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFE6VU5vHr/xO
      iulQ3TNVmUXC37lCMA0GCSqGSIb3DQEBCwUAA4IBAQCTlL5Fqw2joKoVGG8LVkaD
      +oMHseSNIhzH+59296htPsnrkE1wvP/2SBFQDzLwXLWrxp2U8FMz/UNrViCE2sQX
      u7Vru7SyZViSlXmzW3uKhmGPVSWoqX5dncplTOT6caEjDfRaRtsOf1yqwyupiJFc
      EchM3UJNLL7WQ3cU/oxILIi424Zwb5cdoQaPjW5MIdswq6ok6o5cIJbDNPrRlPwm
      rTIj+iHy5NFuKuHlA31nJp7Xd8iXBqruPsqh+iSoM0lrPQ/nUWTqdXRUoJad2RYN
      8vv6wkhxo+VjgXnWSHzfSilMaDXwOLLFV9oN/ibgWOkfcDRlLo4LrUmaZJ8FxUU6
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    creationTimestamp: "2026-06-09T14:16:52Z"
    labels:
      istio.io/config: "true"
    name: istio-ca-root-cert
    namespace: sample
    resourceVersion: "809"
    uid: 2e956eaf-a93e-47c3-a953-e4e50e5cc831
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIITmHMwja0TNkwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjA2MDkxNDEwNThaFw0zNjA2MDYxNDE1NThaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQCvmlvlZu4b0zM6Wy8mcIjGqtg79X6vYLgiIt7Fadqpk1Fbkm2dm23sqovr
      f1YXUfT9ttcMAMOQSIefBifgAIamC8EmQqZTx3Yqh1fwgoosjKeM8ugRkm7XslFL
      W8fMYvE1L2b3mhw7qAHriHhf8w9bYZFsqnxK4lkxkMJbYzEmoiMs7ODAFfpONFr/
      E5A+B6PEyIYn9oL0Jnvl7GBtzVsGLEnp7mHilCtVkHKMcqQcKYt2SzJslcJcVg6T
      972TCZ5jGSBJCMtudlp6cKkgQ5v0ssKshHIGvHSXCGvAJjVu1FmpKJQkqdEd/yDA
      Uqxgz1cfb5AN+yFfN50IPHXARLJVAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRGAe/TNmc+KMlkxXhsoIMVfv1cvzAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQCQ6hNc9my4
      N03ZiKny60ysw6YVI37Ezqj4aVVLur6CNgoHdNfcgxR6aPKZgt+X3RUk5ETMKevW
      ITMB20aIF+jXQB7oYDw6iATNglf94wz48r1aeyjs9w2FYUIZNXru792NRt3TzOV2
      YMwmnu4/G4JlbH7JLxQ6rXGjrqunTJD3Fv9Rl0DIiUXdWD+wNWAGN3w5YKQlUmJg
      /Qz1iK+09o/AfI1X1i/fYi4YqViudtMU035EP/OHAi9eHV4UAl0PXkp9bVIjeH7A
      tySoY72PbGmw+y/TWjo2QUjdaTFvFX3RjnMzhk5r7aGt/9ziyZHfyBXhCBHe6aEl
      Y7gO3z7OPeUt
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-06-09T14:16:52Z"
    name: kube-root-ca.crt
    namespace: sample
    resourceVersion: "808"
    uid: 050722db-be98-414e-8bd0-8e6820872bae
kind: List
metadata:
  resourceVersion: ""
