apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"test-compliant-ingress"},"name":"test-compliant-ingress","namespace":"sample"},"spec":{"ingressClassName":"nginx","rules":[{"host":"test-compliant.local","http":{"paths":[{"backend":{"service":{"name":"sample","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}]}}
    creationTimestamp: "2026-06-01T07:14:56Z"
    generation: 1
    labels:
      app.kubernetes.io/name: test-compliant-ingress
    name: test-compliant-ingress
    namespace: sample
    resourceVersion: "987"
    uid: 4d9d0762-f076-44ed-89b2-559a37dbaf7d
  spec:
    ingressClassName: nginx
    rules:
    - host: test-compliant.local
      http:
        paths:
        - backend:
            service:
              name: sample
              port:
                number: 80
          path: /
          pathType: Prefix
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
