apiVersion: v1
items:
- apiVersion: v1
  data:
    ca-crl.pem: ""
  kind: ConfigMap
  metadata:
    creationTimestamp: "2026-06-03T04:02:36Z"
    labels:
      istio.io/config: "true"
    name: istio-ca-crl
    namespace: sample
    resourceVersion: "579"
    uid: 73153db1-4ac6-4cc0-99d5-4021a59acb74
- apiVersion: v1
  data:
    root-cert.pem: |
      -----BEGIN CERTIFICATE-----
      MIIC/DCCAeSgAwIBAgIQPUBorYLfq5stAa78Me5vYDANBgkqhkiG9w0BAQsFADAY
      MRYwFAYDVQQKEw1jbHVzdGVyLmxvY2FsMB4XDTI2MDYwMzA0MDIzNVoXDTM2MDUz
      MTA0MDIzNVowGDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcN
      AQEBBQADggEPADCCAQoCggEBALSSkv6DInusXFZnCb2s76hzMOzTITbx1N078NqR
      8K522sI90Hakzdk8hymr3GpRAD2qo9FuQwZ7tsQOgSsJUy7gxG4f3Sf+LNh1BZpr
      kdn/08WEQr8KuOIHP8swepTTwdWFnCfFSgxDNFsXTeexgEy2oD33geJ8qgJDlh0k
      enPu9jAhfLAtscKG3ptrhEH2ghX4/eV47Ehalv9SfxSPGYbV3Ltl3dDAi0yRuMrb
      YM8yqO+fngehb7oLmVKGG63hFbVhjEhu/0HUetjlN8Atsx7ViuM+YB2JQAWS/fpT
      okLyxMdFv4A9RxvZkPMX83luBHVEatlE2fMAH69rSs8hEe8CAwEAAaNCMEAwDgYD
      VR0PAQH/BAQDAgIEMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFGm494SOFrIS
      gVzH4GM1YqzRtMUjMA0GCSqGSIb3DQEBCwUAA4IBAQBQmJrd//kRiHt0o+0GcNlg
      xrQn/D25vDMz9BuK4RSxFUUZRwAkM2hT3auDgCVpUCSuc9jMcrm6oegTFm52OoJX
      Z7z8HQFOrwUs5mCNTSdKn+GN2CgJERfGhIG886fsj70Hlk1EV3iO99/q3WRTH5I/
      RqbPorONWvGc/x8AcVW6YVM9tqKlQciw9SJBAE4rOG2qLCeGRimaVbCBzRArN91p
      wWoYSEEJj2elJQrEDbbilu/DZdTZuvHg7oXVKjydGOH6z4AOI0TwQ8JQ+kKyKKh0
      V6pHRXS9HZaWZWgqqnCOp7dlivhdhgTHyUbaAyy/mUnHV2hbBf8uT1VHIHXoRHsk
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    creationTimestamp: "2026-06-03T04:02:36Z"
    labels:
      istio.io/config: "true"
    name: istio-ca-root-cert
    namespace: sample
    resourceVersion: "576"
    uid: 0e9bdbeb-e582-4264-8b83-e1676d9c4e03
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIdYEdEvrtZhIwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjA2MDMwMzU3MDRaFw0zNjA1MzEwNDAyMDRaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQCe9gAr1epn05Ur96b6LOYTLmXq/yHYpwFIIkJWlbDgkXzbUwdkRreXS2dA
      rwnuN+coj0tg/30p+T+RMg0doHcxdkgGpN6Q+h0o3j0aACON8QF/Ra0qt5zpoUuG
      QJEmjjlVI4/ZIuN93PbVtMHwbpoR5TbRgn7HjPkFcJVbtDajoqiDkRm6R+NKQBKw
      HQ0YRN2nE0+HW1y7GENVFt6jPLXrRkyBHvD+0IeAmoaqwY4mYRv7UZNRtMyqUaqO
      edKrFwlQ9ZtHSVF/A42fzBQjkC5CplXxkZ6nFSRJrp+e+tcTXLJ1+nwLqczvgKY3
      vFN0X4cy53qAGnNMh85BtmQ/lxVbAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRHwT6+glsLqIO6c7kLAElBx2wSrTAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQATd2xocn8G
      hmmccWNCWqUk4Uvrr+ZK4WCxoVm85gVOFHzId0pSUQEKDWg2RsEUkj5P76eLCxIf
      PyruBBenlE5ggq3agGIDEU/ZIxDy0mTRGXAmNVGkkrBlxZSLUI7saH5+8sQ6jXQs
      /qiupO1/G6sYPsoXT++zE8HZSIDv7SqW3hvbfT/cpdw/LpPO6ayjFa8iPKJhgV+3
      KlBbjtGAaDoACn0BdQxJS7Jn+NvzZ/hgjp2MNgvexM/TFFdU/Gl/e/jLH3BBmC5y
      gXdBjcGcQQLdKPXHmSHKLjWHHD5y5To512cMjxn4xIH/WYUdfIDKdr3VLhw3f5mJ
      pPMJocMpHz2R
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-06-03T04:02:36Z"
    name: kube-root-ca.crt
    namespace: sample
    resourceVersion: "577"
    uid: 443566fe-8434-4b46-9f69-093b48fc777a
kind: List
metadata:
  resourceVersion: ""
