{{- if .Values.tls.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-tls
  labels:
    app: {{ .Release.Name }}
data:
  tls.conf: |
    server {
      listen {{ .Values.tls.servicePort }} ssl;
      server_name _;
      ssl_certificate     /etc/tls/tls.crt;
      ssl_certificate_key /etc/tls/tls.key;
      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
    }
{{- end }}
