apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    creationTimestamp: "2026-05-31T01:32:23Z"
    generation: 1
    name: sample-basic
    namespace: sample
    resourceVersion: "633"
    uid: b10a5a1b-ff46-4e8d-9330-0921e10fc863
  spec:
    ingressClassName: nginx
    rules:
    - host: sample.test.local
      http:
        paths:
        - backend:
            service:
              name: sample
              port:
                number: 80
          path: /
          pathType: Prefix
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
