apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    creationTimestamp: "2026-05-30T18:13:13Z"
    generation: 1
    name: sample-basic
    namespace: sample
    resourceVersion: "659"
    uid: 70608e7b-e5c1-4685-aa8f-310736c931e9
  spec:
    ingressClassName: nginx
    rules:
    - host: sample.test.local
      http:
        paths:
        - backend:
            service:
              name: sample
              port:
                number: 80
          path: /
          pathType: Prefix
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
