apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIRJt6lTEs5dAwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjA1MzAxMzU2MThaFw0zNjA1MjcxNDAxMThaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQC6gqS2CWwe3a/NGpqqXtoseZPfBjDWvufD9NzvpFZusH6ZBqeQGPgtbKsQ
      8kbzmIxwfmHaUlJbk+lidAg+BZ9X/fjy4Jk0p2esfajUVbryEUsaJBEOL5fRRsLB
      /BHVeaBRUroZrnLJWOtUVUs6hApdgPX7n53KeP0M6Yuwuz2ePe9SDpxnu7Nt+C3M
      uQa06DQ2yYpj+8K2xbZH1I8O2JIr+7PfLUJ+C6cnOSBBnMKj1e5Xe0/QK+dcgcdI
      V96UmQsE6TnL7RF4rPd3ufK7E5GHY68hvIqCs1GUoX4wuNQMeQ4msJafHT/qYDev
      abThbxu4ptZYkuvENuwD9vd2hdVVAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRPXXIX8jyAoLVTwndUojRKvxOwhTAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQAYGOX2wuWZ
      uguNQR93dW2OK8zZ65kzsKrs/LKBwegDoXNDmUzce+dKiuLvozyvuZheyNuQPqvU
      AU7OgAIT9ftpNZjn7W2Q4+cJdHQgdl820fJd+beOVb1zDTRrIgfAYZfjGbCanKdJ
      Nds/wYLCC4BZtCrDTv7Ze7TA8+zFT/EXOald+7CQ3elqEBo6pE1ySOh0TlAPaIX7
      cEjuYgecPMK5PxY1PQSQpItWdSgsEM0pSTwqdoS/6VmDjQByWB+gsCh45z67ExEd
      Yi0hJAu65lCvKIiN0sfWCtfZb1omIWGSkga+qwQ9vycoJ8WNfiDNYIQz/S9nrb1z
      NrHq/3LHaeEV
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-05-30T14:01:44Z"
    name: kube-root-ca.crt
    namespace: sample
    resourceVersion: "464"
    uid: 5185d3d3-fa5a-429b-97c7-9fc80008662c
- apiVersion: v1
  data:
    tls.crt.b64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROekNDQWgrZ0F3SUJBZ0lVZlFCUlZibFVQanBMbnZtckFXeUl0ZkMzV2VZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0hERWFNQmdHQTFVRUF3d1JjMkZ0Y0d4bExuTmhiWEJzWlM1emRtTXdIaGNOTWpZd05UTXdNREExTVRReApXaGNOTWpjd05UTXdNREExTVRReFdqQWNNUm93R0FZRFZRUUREQkZ6WVcxd2JHVXVjMkZ0Y0d4bExuTjJZekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTDlPVUl4M0wzVTdCNURjR2dvRTJnMk8KV0RGS2MrYVNab1NkMGQ0d1A4MUFUbjBSdUNRa3hBMHhIMXYvMUNYYWNUZytFY0dnWWFzaWFWUXVFN250Q2ZPRQpMMFYxSHJzOGlmdktHMEp0TmQzczUwUzBwbVlEZmM3Yk1TTEFJM0JZajMvTGFLd2ZGdHpqM2dsd0M5Tm1FV3J1CmZ4V3FQVytMR3hUYS9waGF6NTgrRnU5UDhtWDZzNVR5dFRQZEdEdjAvT2ZHSUhwZjZSQ3pNQ1VvN3paeThPanoKRVhCWmFTcnVzNXpGOTlwS2h3dW5NSHJWbi83VmxJaUpiTjI4aW9YS2c4eEVBOXRZRTJGcjczYjRWZnorN3dZUAplR0pNcVRwL29ybDJGUHdNU09MUE04bXE1c0tVeGw2YlhNVFU2eDd2WkVsTHRmNzBzNk9lZlhFUEtnbXAzYlVDCkF3RUFBYU54TUc4d0hRWURWUjBPQkJZRUZPajJyYmFBTUdQd2FkS051K0NWUUNOL1pVUllNQjhHQTFVZEl3UVkKTUJhQUZPajJyYmFBTUdQd2FkS051K0NWUUNOL1pVUllNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIQVlEVlIwUgpCQlV3RTRJUmMyRnRjR3hsTG5OaGJYQnNaUzV6ZG1Nd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCTmNrcCs4CjRuQzdsM0NZVnMvcmxleTZ5TGlaU0h1Z29VZnFQK1RHeldZRG9HYUJMNVRJYW54cllkMUFiSEdIaFNocXJ5c1gKTXF2RHFjSWNvTWFtN2N6dVF0ZGRZSHJzeFNQcHFlT2RYd2R0VE9jZGZVdWp3elBjU2JOaUljNldNekRneUZCNgphaEdlMVJjQUp3ODBQYXA3NG56WlBmNjAyQkdqcHJSQS8yeFdXNDhzOUpKZ3M3VENUOVpxeXlVWHNjNzhLMTNxClhtbEUvU2FkaS9sREJOVHF4Mm9idk1tWkdBUkpxUHJjVDQ2VHd2UFRvOW1URDBOWE5pek15QXI3a2RvNkVHSVIKMGYzL21vRmRtcnZBY1lDN2Q4ZDNHbVNhRzFabkpyWkFHOUlTdW93ODJ1RFI4KzIwUDB0SzhuOHNzVHF6eGJsagp3Y1RvRXgzQ3NDV2pUZkU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key.b64: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQy9UbENNZHk5MU93ZVEKM0JvS0JOb05qbGd4U25QbWttYUVuZEhlTUQvTlFFNTlFYmdrSk1RTk1SOWIvOVFsMm5FNFBoSEJvR0dySW1sVQpMaE81N1FuemhDOUZkUjY3UEluN3lodENiVFhkN09kRXRLWm1BMzNPMnpFaXdDTndXSTkveTJpc0h4YmM0OTRKCmNBdlRaaEZxN244VnFqMXZpeHNVMnY2WVdzK2ZQaGJ2VC9KbCtyT1U4clV6M1JnNzlQem54aUI2WCtrUXN6QWwKS084MmN2RG84eEZ3V1drcTdyT2N4ZmZhU29jTHB6QjYxWi8rMVpTSWlXemR2SXFGeW9QTVJBUGJXQk5oYSs5MgorRlg4L3U4R0QzaGlUS2s2ZjZLNWRoVDhERWppenpQSnF1YkNsTVplbTF6RTFPc2U3MlJKUzdYKzlMT2pubjF4CkR5b0pxZDIxQWdNQkFBRUNnZ0VBR0cwM2U3ZjhKMHZTTzN6ZkZraG9UekxOci8yQnJ2OGlkK3h1ejUvNWhZdWcKZWZlNU8yUTJaRGpSZUQzQ0tOTXJnYkxyTVgzNCtwRDZRZlZnTDIxRXlBTW94Z1dlVnVuejlHSnArS0ZaTDIwQQpXcFYyYWJBb2NERXNwUE5Ea3lTN3JlV2JCOTh3WENQOFJkZzRxbFZ1QStsUDhNUTc4L0lmRXhxalIzRFE4ZFFUCkxmc3hIUldLSTJERFFtRCs5NXppWjRxNlVYZHdGT1FqTGg5V2E4Mm9xVjJuYUtyQ0dvNDNQRUNBaSszVXhFcngKQlJGQ3RXRFpoS1E2UkQwbTFmRzB1RDRqUkMxYmpzSm1OT0RWSEkvWUduZUN3NFV3czAveWt2bDNQa2x6aGdmcApMTy9KSEpzTU1UY2ZWUHd2M29ORWdsWC9PN1JHZUZrektMcDk0QnhZUVFLQmdRRGt6bGRCWjRJOFV0UTYvMWMvCkZ4NUtnY0QxYTU5dGRuaEFlbE9rTjJ4Rk0zZmFsdzVWdmJjdnd2cHlibzRjWmh5V2VnbG1ha2txZUZPSE9hSXoKdGxLc2xSTlBxVFR0SFJZbkUzT2hWUThqU2FpNUhwTzNWOXJUd0hsZnZsYTBhQWNvdTJ2MEF5N3lZeUxnYzBDWQpUS29FQ0g5U0FEc3VqOTVVTE90bktmQVJkd0tCZ1FEV0N2Nlh4dlNTNHROaUg5V1h4M2xqZE1yYzIwMW9JcXJICjh6TWloSWZDQXFCa0xXc05ZK2dwOUhyYXMwQVJBWkxDb1VkV1FiZUZ5OEIwVDY5Szk5Vit6ZDBqdWpIWGxDNzIKTFhXM0x1SHlsRWFHb3UydUU1S0VlMCtialB3Q29SblByZ2h1TlR4eE9JNEJrOHY1NWNFZmVFY3orVHVuN3d5bwplUk5uL3IxMU13S0JnRFpvV3BkUzVjVXliUVVhY3NTdDJxWWM5S1ZuVWlIVmFnTHJFN2lZOVVYL1Z5RERpc1VZCnQ5YkRwb3BQZjd1QkRJczd1Y0NBeGFVenQ2a1FLMkhnbVFndzZzYW1sYzlNZTFnUGFBK1ZDbVI1djRWRm9CcVkKNlpBdzFLdlB0dzV2TGtTaFRLcFpsM0JMNHA4OHlMOXVlMzg2Qmd5WndYancvUTFISVRNRzVlOUJBb0dCQU11MgpieFM1TUhEVUhPY1k4VXFoZVBDbGFhWEZ1dWhQaGtjRE9qbXg5UnM3TUxmbldpbkdXbUlENHlGZTFLemEySGtRCjBqcFFGWURycU9HS0xZV21WclYyN085aCtLbjZ5SzlZR044ZGFjSmNTTHMvT2dNaGNhTlJVVFQwZTYxczhvbnMKVXUzQkVTT1k5ZDZlY2RZSFMwVE9Uc1l5Z1FxVnczQmN1NUdRcTNSdEFvR0FBaTVPQUIxeWg1OFc3MzZubjFoSwpVYWlvWTMwc2NrWDFNbkhDbDNWazRZcE5NSFFGcnJTTVByajB4YTFVVGJVaVF1dUhIRnZPdmlsNSs3TnpaUW9nCnhsT1VwdlZHTllHWm9mUUZVa0ZISHhHOW43TlJhVnBnNU02KzlQaXY2L2lHQTlIMnpKcW02Q3dwZWdROU00aGsKU3hFczVWUTg1UHBVcmZPODVCUXlDb0k9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  kind: ConfigMap
  metadata:
    creationTimestamp: "2026-05-30T14:01:45Z"
    name: mounted-tls-pvc-certs
    namespace: sample
    resourceVersion: "477"
    uid: 6e6ead43-bed9-4c03-9ebd-f60f8ed5512f
- apiVersion: v1
  data:
    default.conf: |
      server {
        listen 80;
        server_name _;
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }
      server {
        listen 443 ssl;
        server_name _;
        ssl_certificate     /etc/tls/tls.crt;
        ssl_certificate_key /etc/tls/tls.key;
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: sample
      meta.helm.sh/release-namespace: sample
    creationTimestamp: "2026-05-30T14:01:45Z"
    labels:
      app: sample
      app.kubernetes.io/managed-by: Helm
    name: sample-nginx-tls
    namespace: sample
    resourceVersion: "491"
    uid: 9d78dc24-bf26-4534-aaf9-3283bd2b2f84
kind: List
metadata:
  resourceVersion: ""
