apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIDtXZUWFKlkgwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjA2MDkxMjU0MjFaFw0zNjA2MDYxMjU5MjFaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQC6iqqulB1YXNK4u4lgMPTRBuStKpgjwHGFireNjHYCDg8DyfU9+uErD+zE
      EYX4AYC2SHGPWn1Yne5J/z3WSs0ohnylo9G3EH4VR8S2NfkkQ/6Nx1Zcxmb3RMeT
      V7XSrfQJMXzsNfGkWYnWL0iMtLpZz0Nt6dT8C4PoSxv62lMt5pGFxl/kvg48kEkl
      KurKGp2QzqtXhoCoKPBZnP7qKRUlJJcenRXXN/zFGJ5GU/UwskEOV0+d9LX8NzEx
      Zamx0SC+PGSmy/P/Q35xIrWTbHe2ppx3rV3X0LPJdbY8m+i/i+iA2tW48GN7c3b8
      xa5Vz0ocWM1xsWBtghAlE9v0+vujAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTev4rd245cX0UBi99Om0SsVahV8TAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQAGdd5JWzgd
      9swEz8xvj8xb5SpDvJ/jsonw5jfemJ3Aq8dOVCbAocyzOn7YXM+UBaJtDA1ZwvDG
      +Bu5wrGXWlfNv/Jw9Ievmn1zATMfUM9WiI3FkkABwbeTmi4e/pTomLr5wSu/15Xl
      3KqI2RY0cNgz6vrALhBg3T60Y5pLBEsqykFToFNRK1G/f35SPNM8Q7PDx4sR6h2B
      4iikGa8jBUEEYoREc9uhc7LaCWm7xOc8lHZx2g/1ARlpi7B54WFAM5MrIgP19yxD
      guzQqj03cQa8zgKz6Mwxz752pxFTpqIpSwr7MNR4z1vZ7OnFddc8AxdHAjRri3Jy
      gPpHG+7Mac42
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-06-09T12:59:46Z"
    name: kube-root-ca.crt
    namespace: sample
    resourceVersion: "463"
    uid: ad4e71a5-40be-47a4-a3d9-106242e08346
kind: List
metadata:
  resourceVersion: ""
