apiVersion: v1
items:
- apiVersion: v1
  data:
    ca-crl.pem: ""
  kind: ConfigMap
  metadata:
    creationTimestamp: "2026-06-03T03:58:05Z"
    labels:
      istio.io/config: "true"
    name: istio-ca-crl
    namespace: sample
    resourceVersion: "641"
    uid: f5f8a79d-fb5b-4b02-94ee-de51d61f81ea
- apiVersion: v1
  data:
    root-cert.pem: |
      -----BEGIN CERTIFICATE-----
      MIIC/DCCAeSgAwIBAgIQHP+BZvxy1DuiXFjMQGBmOTANBgkqhkiG9w0BAQsFADAY
      MRYwFAYDVQQKEw1jbHVzdGVyLmxvY2FsMB4XDTI2MDYwMzAzNTc1NloXDTM2MDUz
      MTAzNTc1NlowGDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcN
      AQEBBQADggEPADCCAQoCggEBAMvxwYKj+6vbFNA/HTCvxH/ghuzvKsFdancfYtSy
      RYcd/yWoE+29PRbJyHCsipL4IeZipHnT2StWRjAe+X+se+T4HR0BWqNwEsb0vBl6
      4gorO4ce40CMctH+EkSRcEpuQSvy+0cp0WS76WIC4lQ158QDjbWS1sAbtPzYObqQ
      FjCETcHPjT5QTzD27yQ+0qvM8iUgqEKF2qK3GvfuA9PxqNrHlbZMiJXLXEoG626p
      RtiNAnAWjzo/52IwDAO8IwIli1B3Y6efZDqs3dx7pXmYBpUvrjV58eQCXFFexSVx
      LB3Pl8icPWd9b58J+yOaNY7+VbxYxSZw14p44UrCIw6aZt0CAwEAAaNCMEAwDgYD
      VR0PAQH/BAQDAgIEMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFNKnRHg+FaAM
      CPi/rxwt1zOWtyVTMA0GCSqGSIb3DQEBCwUAA4IBAQArLEq4Bqh31n4um0XU7nXd
      jafcbpprrlpITKSjsTF3BvV8yGBVcXMrYiaoiZgzkBQtQEF82jwxjiiOiUNuQhjG
      eUbgxs+jDS3zRA1QFsBVesnL46afVE5sUEnW2C8/CKjbI+ge9ZrDR2C5A02qsADc
      g66qovDTGh7wIGQnJ9mVUANlGHyCPUOO3WEJT+jvUsVjSKbr9+ytOIgVlGkb7eaY
      4W6MKNsGnb//KToDzIBXiby/Ol0nJnX1i5SiGKnlbu1HZSavmhXMrFS3PvC65oy2
      60ixp1T2Pkxh95CIGWrEDNk8l0h+O5Foj4XGCb4bW/UbOIeQeyQn+Aohv9fIeTnF
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    creationTimestamp: "2026-06-03T03:58:05Z"
    labels:
      istio.io/config: "true"
    name: istio-ca-root-cert
    namespace: sample
    resourceVersion: "638"
    uid: 977f19f7-2878-4727-a39b-67905b5f40ef
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIQ6sXh+z8+LwwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjA2MDMwMzUyMjdaFw0zNjA1MzEwMzU3MjdaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQD282JARN8WLlaa6Vw80cr3gMm+VPPk0h1PCvtrVvh7fKC5xDKX3/Ufg4DL
      sCbKFJttJDWa1NYERwjZaIkJE5b1B05HWuo7FqIHPvMvbYpf/0J+ZszKrJWnq0lQ
      FQW1v5xXfsbtDQG0pD0utl7HrgGGDSOvZPMtpnN3C9+P2CkU3/3Bf5AQ/NKLah6p
      wz4HYmCE6wKL5Elii6Icw1nFJzzFq0CM8lx6sfltYppqqIwwoRQAFmT8vviendzI
      AjGfnl2IR+sLDmowHlnJ1nmDgpaqMXkM3a4yQJZs2t26hABBZ+bZGmy9k7PNKu/p
      Miys2IH1+q65xIECJ2MUnD7xgxvlAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBS3mtaMHYr5ww+vkVerFaKfMFNPSzAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQBGQTRtdmq0
      T7uXuPFxDBphuUvG3MXJBJ4KYbzyUZy2CLdZoUsye4nAGwSMAx/nSjeurEbwN0SI
      deifUrCPFv0xT/Gep6sjJLlXym65e0It0Miq60UjPCbZhpnWa5TGQ8OEfOV+Er5Z
      HmIxWqicOoPKe1xVeqzst2d+S3Cwit+o0jqJlTcyHFKYPfyN0S4kbgebnMbV5C1c
      WZlfh8jDYlFracF/46vdA+5du0UzQ9K40cUMPU2GRGDXOcQJn4lxmhTCDFKy9ayt
      06xqY+/AmU5WBf4uhf33vFIZ/qaDl0ERxdoDPYCjMYcqnSqyx0CdxB2q5heDemDd
      M073z8nSTAxt
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-06-03T03:58:05Z"
    name: kube-root-ca.crt
    namespace: sample
    resourceVersion: "640"
    uid: a324092c-1d8b-4e7d-bc86-43221be0e140
kind: List
metadata:
  resourceVersion: ""
