apiVersion: v1
items:
- apiVersion: gateway.networking.k8s.io/v1
  kind: GatewayClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"gateway.networking.k8s.io/v1","kind":"GatewayClass","metadata":{"annotations":{},"name":"contour"},"spec":{"controllerName":"projectcontour.io/gateway-controller"}}
    creationTimestamp: "2026-05-31T23:22:42Z"
    generation: 1
    name: contour
    resourceVersion: "582"
    uid: 9348325a-1ae4-4988-8ec5-38bc6ebabcaa
  spec:
    controllerName: projectcontour.io/gateway-controller
  status:
    conditions:
    - lastTransitionTime: "2026-05-31T23:22:42Z"
      message: Gateway API CRD bundle version v1.3.0 is supported.
      observedGeneration: 1
      reason: SupportedVersion
      status: "True"
      type: SupportedVersion
    - lastTransitionTime: "2026-05-31T23:22:42Z"
      message: GatewayClass has been accepted by the controller
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
kind: List
metadata:
  resourceVersion: ""
