apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIHSFgB1ZP6C4wDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjA2MDgxNDQ2MTZaFw0zNjA2MDUxNDUxMTZaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQCqHqVOr8zpqm9BbCQb0Zv2ztQ/oGgMxuXSsWutPvBVDaP1EfvY3Fyr9Bpo
      px045bwIhVDxlIsztq/1AuA2ZaVqBCJxLg3frIVLqUGuN04Yxf3KMBhIfTjTWCO1
      dXVDLqaf0BXvCd3sOaOzhSIP+kvBjX5X9snQDqp9s0t/a58xao+xgTh1mC3iR6Qm
      rqspPUWp0n4szyAb6FUw6OkJ4M5bflSehlWpuYE7Zux4vJaCi3tjQf4jq5zYHpik
      48qiCoUY3TdGhk4Qlq19kzMCGEeRo7HeoEnbkjBKHVtC3l9ox868kWpRo38+uot0
      sgwgws6FgXhG7Gwlwdj6kZDOqHTLAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQzOLlhI6OUEIVfylLmOl2ZbyQBFzAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQBSGbAfpDSg
      BNNCj+YiUSBOqVIl2AK1ZgXrWCH+mh0xU+aelvZWB7VqcK4W6iByuK0+yptAib09
      f3hSI4uIt/aPyv4daWwnvmP0iZx+/obLvzYLQIjb3YDOh1Xoy0YSWg/Um6yNi0Jd
      X53iJ4c7TnVag+hHXOu6ib3ITAE8P81FSc0vcrJob+YiNmBPC87zdQQEcVzWSEqf
      G/eBU/RL+VGVUhMlToBm/yiG+aK0HA6rg4lUTp+t7jclmRPugMvx8T19KR0N25wr
      0mQPbcU9EN7Mobuf8B81qL1/ZlSfId5sSaq9dJY2AWNOQH+C5waDTt2OrPBpAgLP
      v0XoR+lwi4A9
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-06-08T14:51:39Z"
    name: kube-root-ca.crt
    namespace: sample
    resourceVersion: "410"
    uid: ac6b613c-100b-48cc-8248-2414a95b8b39
kind: List
metadata:
  resourceVersion: ""
