apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIUYqkOPgAS1UwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjA2MDkxMzEyNDVaFw0zNjA2MDYxMzE3NDVaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQCvBXEwLh1YATXbTLfdNLI1og5hj6KqzxDDxN6DVJbdD7smqAnsZEgMhZZi
      yzW4DZOVjzUdnvGPF1YG+TOQ9wiIBZUJa8qsFhry0jpieZ3JTZgxepzIHHvxJ7/t
      TsEmsRfxUnSDk0IbZm9kScA4/EFK43qY/Vcg8I2HjkC2e+I30WAGQOA4KX+bMs7z
      0HCB9GR9ohpUzOmZEj00ZkIeQXTsjtpc+36a+RBnihZwK72hT8x35AEOmbPHGD5u
      KJMvkZBFn8lUb/hQbQ8R8tWYdiCnr25VKvrxm5EFq15f1v+tV7wLYV7p/cZNp4OJ
      XBtt6OFe2Fq8bZYXcoI7jTsP6aKxAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBR9DEhHLtsofYm8LjS+o1rHunr04jAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQBKWjztUMj6
      OlG7jE5ubUCwyrIFGbkCjhuRfbETXSmzzHdsF3gLgDNkkmJNdcth+/+H2YdMk1FO
      w6GAlwmgIpkS/Xw7tcgJ3rYOMU4/bDOGJZy/HjGf3oIO1cwKZFE9iSXW2kihxHZK
      Nzi45b+RyiczyOFyyfzc7dCI0egzQbtoFsMEVEk1N+l6I8x0hMhvWRWQeXjThvgu
      bgbd7qH7KFQ/tQaB1DZuITLl8HTyB+N7fd11tsQitaDigy2Np4lC9YNs8gAxEVYr
      4U7YFWsCakwtdYTzthIQ0ZQJBs1BEPQ96P6270/CY8cTdJm11bHWK/XLta/IAAnd
      IPlvfQ5Y+uS7
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-06-09T13:18:08Z"
    name: kube-root-ca.crt
    namespace: sample
    resourceVersion: "422"
    uid: 0fe8c2e4-6126-4683-b3d1-1ed255b22bc0
- apiVersion: v1
  data:
    default.conf: |
      server {
        listen 80;
        server_name _;
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }
      server {
        listen 443 ssl;
        server_name _;
        ssl_certificate     /etc/tls/tls.crt;
        ssl_certificate_key /etc/tls/tls.key;
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: sample
      meta.helm.sh/release-namespace: sample
    creationTimestamp: "2026-06-09T13:18:09Z"
    labels:
      app: sample
      app.kubernetes.io/managed-by: Helm
    name: sample-nginx-tls
    namespace: sample
    resourceVersion: "435"
    uid: 2c553f47-6c95-4f3b-9389-93de4a061ef3
kind: List
metadata:
  resourceVersion: ""
