apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIICbHIavDFuuMwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjA2MDgxNjQ5MzBaFw0zNjA2MDUxNjU0MzBaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQDh220UfV70SnPODFwXqPhcIDRcYEULMHb5SXX28M9ftPVrTQn29lWkJGhc
      /g0Mpqm0isAjTF7e1mbNkgxgT5CjcwaCu4nVXAXH6oDE+llJSAU2vT7LvqydgwUB
      bCtusZrj9ejzPWLvJi+VK9nycEbRBIvl8wQzKXriZDJ1FPVsLsKR1fmqwo97ERH+
      1lt8zaHcRRcR8Yv0IEFHmK+0V2++Xt7OCw+z49vBNQl8H5DdRdctm/n4MvoWtIoP
      8KQbU3RI51sR8khmIPsnfPDsafknIDn+RuPcAIfYT+oER+dPg60NdHNlSem375Gq
      uFiuTObbGR3p9/akYb+pdpIpDO5LAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSQ3RE41cE5GUd0f7JsaX+tC3yx6DAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQBETLmaOD/H
      cGS85HZo/PfU9F++6SR5d+fCswsuJVdLdJnLXGY1hMZwQIMIEQhSY/MG9LLIo/je
      JEOOmp7j1aiS6zO2Q+/OrI0GvtzbGAdoHF/jzRhQvS2yOciy+Zf7uPvHX6BoUBD8
      DvHs5inYMhl5XDTbMur8U8REV72Th0VjUc6HRP2yyngYF7PUjpG3SsCzJ7FluSpa
      dHBUX4jbljGFXMy171bo3FIVP1olEmSvCT/3X29O/HS5SkG4pvlOmfJU6p4tu3NO
      RXnpMJONci1Fm9LC45ykWGWN7tO0ZAh1Qubl+/eyvWOIFvy0gWOZNBzD3t2fIl+L
      00ewjl66e7nQ
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-06-08T16:54:55Z"
    name: kube-root-ca.crt
    namespace: sample
    resourceVersion: "419"
    uid: b5044275-86d0-4650-94dc-d7ef879113b9
kind: List
metadata:
  resourceVersion: ""
