apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    creationTimestamp: "2026-05-30T18:19:39Z"
    generation: 1
    name: sample-tls
    namespace: sample
    resourceVersion: "857"
    uid: 6ea35926-452d-4b3b-b700-1c6ec723258b
  spec:
    ingressClassName: nginx
    rules:
    - host: sample.test.local
      http:
        paths:
        - backend:
            service:
              name: sample
              port:
                number: 80
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - sample.test.local
      secretName: sample-tls
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
