apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIdzWfWo52PDEwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjA2MDUxMzU2MTdaFw0zNjA2MDIxNDAxMTdaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQC2wo/pyBhhRIt90/EVtHT0XyUwOat+3aYBT+fHaePtEvhqW30xNMoER3B2
      kANISTfv4QowGowz7zg86LVB/QKeNjlPY3aK3oibFn86HSXqiGQXb6r5pHwlUNFy
      aVqRKk4GuSISA0WLb11aSdGJXGifTZYIdk0by8+dzm8LvXx1VAxOlLmxup4ESl1y
      wTVHu/QvxCoi9NgfuGGvROFmo6CtgSjjv8wOt1IetDW0KCZyNAK4zVxBq9oFM3KU
      nO4Qd2z9NXUNucUKamKWZB6DIOvVlUi00i6H9BPtI7+2YU4YRrOTSaI68v6S62VJ
      5FZzVetbwMUnD9jlicgAZVY1bnc5AgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSCTo7Iu0JaVp6pkT3kfuLyALdlNjAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQAR9jUHrA8d
      xJSsN0PY7E3cV1nJpxgtlImw24n+5p/d8he2XUnjHvyLZan3SDWW7QS87MZEkk8N
      Z0j0B+j/pub1fRRAGuf0JC7tw1/z7StHCn7yRgrQVIyHvBO2Kso/Bb6FdILFpBtQ
      p84DjptdPxMsD0LlnOJUGjcrMOHM2iAcftvD/uQQ55FhYHYuqdPGqI6slXpwDqo1
      b0QQKv3OzXwUG1HUNK/UDVafcP+Tu9TYduES1yesQL17txfPdpMk7WDQApxtf3X4
      ZYJ3a5+T0GUR4AMtSVdYsRC1lNudSEu4IMcSwlu+csCFAqxxg1ja2Cz7VERN8Gh4
      Etvp/CKHOkm8
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-06-05T14:01:42Z"
    name: kube-root-ca.crt
    namespace: sample
    resourceVersion: "418"
    uid: 4557cf20-87c4-425e-929c-93d61652eac3
kind: List
metadata:
  resourceVersion: ""
