apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIbpOgOorW3BowDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjA2MDgxNDQ1NDRaFw0zNjA2MDUxNDUwNDRaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQC5bVvy1Xgk93K9YbbURo9SwIJHiwWW0vMH3lhy89zKvAgrn22g05JxBBtG
      4TC7vZ8yKGdsUc/ymh010RW5tJk0e7szIBBQ+QTvB+/tTfGK+lcuc/yC6mQIbsX3
      D/yiDkSsiCgvLIkjaPjr+dlx5pK9POe8DkOOS1R+Gva5kuF7TvKfeFtP6NBx/4wU
      ffBU/IQq+CX8J1FBna26D171bdJrQ+BCV6PE8/ruaC4gMcUi2DW5wuEUSziGi88j
      RDNGaEZfcFYYKZHoFEMjA+DZvFO/hihMJ+BY35vXxlOSPxTluRZEdXUrttl4I1yo
      8R+gSPZwrFmxJpB6Hl4/btHZyEfFAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTeIxLd5gdA6G0wr9VYXd8X3BOjHjAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQCjdm6doz2j
      3L12UAkRXSz7uVH43YwAuFS+NiG0SzgJSjbo/CAP/4ulPtJhrmREDzeOaDTM9ygE
      9nn9u3uIVIYo8pNG/aiYptj3Af9ykQX5A5W2avYQbWl/1k5uWNVAoIXtxYO74jCU
      VsXxWj5PWW1PvnNlTQShlyC4O0XmBtik1K1hZ09i3SWB23+nQ2jypuOOCDmRsHIQ
      chPZvfSIwoiAH3BE6ZMDBP0JqKhvSHUMpHyVdg2tDFKFSQ9+IY9Ufj5K1leEZcgF
      dUNYtTW28CWul08nVhM/xhUrSJ6WkdoWwn/clgTOs5OMkGr9SHPp03lfIFUDDqeP
      5BhH75U9lyH7
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-06-08T14:51:08Z"
    name: kube-root-ca.crt
    namespace: sample
    resourceVersion: "456"
    uid: 64c4d8ed-d486-47aa-871b-2abe8d040ab8
kind: List
metadata:
  resourceVersion: ""
