apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2026-06-01T15:07:02Z"
    name: grpc-backend
    namespace: sample
    resourceVersion: "666"
    uid: e3a4987f-8e49-4199-95d8-ef3df40ba9d5
  spec:
    clusterIP: 10.96.64.119
    clusterIPs:
    - 10.96.64.119
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: grpc
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      app: grpc-backend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: sample
      meta.helm.sh/release-namespace: sample
    creationTimestamp: "2026-06-01T15:07:03Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    name: sample
    namespace: sample
    resourceVersion: "681"
    uid: 3093a93a-75f9-47d7-a651-3f1325fed4f2
  spec:
    clusterIP: 10.96.69.211
    clusterIPs:
    - 10.96.69.211
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: sample
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
