apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      nginx.ingress.kubernetes.io/canary: "true"
      nginx.ingress.kubernetes.io/canary-weight: "20"
    creationTimestamp: "2026-05-31T01:37:17Z"
    generation: 1
    name: sample-canary
    namespace: sample
    resourceVersion: "965"
    uid: e1bad61c-aa68-402d-baea-1228b67c7222
  spec:
    ingressClassName: nginx
    rules:
    - host: sample.test.local
      http:
        paths:
        - backend:
            service:
              name: sample-canary
              port:
                number: 80
          path: /
          pathType: Prefix
  status:
    loadBalancer:
      ingress:
      - ip: 10.96.95.241
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    creationTimestamp: "2026-05-31T01:37:17Z"
    generation: 1
    name: sample-stable
    namespace: sample
    resourceVersion: "966"
    uid: af805fdf-0391-4aa0-a80b-73e3b534d65c
  spec:
    ingressClassName: nginx
    rules:
    - host: sample.test.local
      http:
        paths:
        - backend:
            service:
              name: sample
              port:
                number: 80
          path: /
          pathType: Prefix
  status:
    loadBalancer:
      ingress:
      - ip: 10.96.95.241
kind: List
metadata:
  resourceVersion: ""
