apiVersion: v1
items:
- apiVersion: v1
  data:
    release: SDRzSUFBQUFBQUFDLzVSV2IzT3l1aEwvS3BuY3Qyb0RWcXZNbkJkaUg1VStyYTNXaW5LOWN5YUVDTFFoWkVqUVlzZnZmaWRZMGY2Wm51Y3daQVkyMmQzZmIzZXp5UnZrT0tIUWdoSW5nbEZZZ3pGZnA5QjZnK3M0aytydmdBcVdGalNBRmpTUjJhNmpWdDNzem95V2hRenI4cXBoZEV5emFkVFJwWVVRckVHRy83VktRQ1hKWXFIaWxFTUxPbHdxekJnZ3FVYWpOQjZwc01vbHRHQmxkMStESk1LWjBpZ1RxbkNBRmRiZkg1alVSWllHT1ZHd0JqYzBrd2Z6cUdFMHZqcTlpM21jWUFha3dqeW94eHlVMWtFdWFRQlVDb0kwWEtkcGNKRFdGWldxTHJjNFMyQU5ZaEhQSytNYnM1U0lrOFJvb05LZEtvUUdob1ZnTWNHbDEzME5zcFM4UUl2bmpOV2dvb2xnV0ZFSnJmOVdSQ3JoeFlGNlFybHFGRGhobWtISkdTNFh0cGduODRLWWJPTS9wK0Z5WVc5SjBUWHZKaUxEYnV2bFByWi9lUXRiK2sybVBMZUYrb25CZ3VIZ1pibVlSdmRoR2pyRFZ1UzdUMjFucEs2Y2Z1dlJjMS9aY2pGbXR5K2xQRnd2MEcrbmI4dWxlOFA4MFYyN0gvZENwMjlIWk5UN1VZYzBiYmJjcFZxMzBQNnhPNDdJTGcxcFU0YTN6SXY4MFp5Um9sWE5UY3l1NGZQSjBkK3V0Tm1jYnNpenR0RUxuYUVSQmNOeE9oc09Zczk5M1pYWSszK0d4ZW5ieUhPTnJUOGNJRzlXMmZzWWg0T3RUendQUThmMFByYXZhTkhMbjVLNTlOekJ6bnRzM1M5ZGd6a2pvL3Nla3gwWnpwL1BiRDM3WmdzdFhaWjdpNXN6dkhxZzBFOEd5cHNkOG5YdXkrbmJ3bmNIWE04NXZPVGtMdDFYdzF2YzVkZzFJczk4eWtreTMvck5zUWlHM1lJKzJ0MzFUSlRZNXNsQUJ1NThkNXN3dFhRRGRzdW5rVmZZM2ZXajgvdGt2eGM2STN0RCtQUVRwbklvWnpqZStId2FZYmZGQ05QckptM25PdnlNc2ZEY3dVdTVwam1la0tRYlYzRTlHM2cwUmVSWHdJTHJOS1NGdlYwdXB1bDkzTnZjOXUydDM3eEI5M0h2OHE1dmQvdmhYMy9CR2t6U1FNVmwzVmRkQTgzUWxZVzZsdGxwR08wMmFobGRkUFhlT1BhMWI3YUpwTmttSnZRZjlrancvT3MzTmxudVhhZmhremt2Z29ROWV4T2h2TVUwOG9ZRHRDeTUyTG5PNzQ5NTUrT3Q1eDVxSlJpeHJjN1pwL3JlZVlzYkU3dGpuWXNXR1Q3OVVOK0RMYmsrNnQ4d2Z6aVBpUG1VejNTZDZCeFAwaTk1dTMwOHh0SCttSDgrWm9SN1lxbHJaZGd0Z3Y2Ny9pRjNhTG00NGQ1aU9xbHkwRXYvSWY1TnM0SE1UdE84N0JqSHhyMy9YdzF1TU10MXgzcURjWUpEcWo4eUtsSVpxelFyb0FWNUdQTlgzZjV3V0RaRDg2cU9tWWc1MWQwdm8yVXo3S2M1VjlBeWF2QTllZHFLU0hWejc2Q3FjL1paTGhYTm5BZTQzOWVnSkJGTjhMRjFIdjVPNkJGQ1JyMThad2haNWV2QkdsekhUR005NlB6QTFlZzJMbEc3YmFCbXAxUFZHa3d3ajlkVUttakJlcjIrNHY4QmoybWVFV3FCajZmTnhmZkZ1T0tuazhJQ0cyUEZYMkllV09EeHNHYkZqOGVZdGVJQTZMbytHbDV4S1NncHhUb1dGcWhDb1VXU01rcFVtcFh6QUdBaFRub0E2RERLOTZsNitXZUJEanI4QTZCd0ZsTDFVRW4vbE5lbnMrZ2pOU3lFdkRqeHU2N1cva2dSQUlaOXl1UjNOQ3I2N3dVakxXQjhRejNCaWtTMzUxYStoT05JNGFoeGprYy83S1AyRjMwQUtpejZJU2xYT09ZME8xZXB2elBEUXB5RUFKVDd3d0tydzVhd3pyYkNDcDZ2TzgvWXlXVGw2ZUZUQ3ZXVFVSekVuRXI1a0tVKy9hUWJLU1dHVkZuZ0RRaXNJZ3RjMUtvNkFQc1ZQNzhjR2JXeW9VcUJ5WWY3b0w2MUZIOG5WRVdwdnRKSmllSCsvd0VBQVAvL3ZKZis2RFlLQUFBPQ==
  kind: Secret
  metadata:
    creationTimestamp: "2026-05-29T19:01:47Z"
    labels:
      modifiedAt: "1780081310"
      name: sample
      owner: helm
      status: deployed
      version: "1"
    name: sh.helm.release.v1.sample.v1
    namespace: sample
    resourceVersion: "683"
    uid: 53b9e985-a1b0-456b-8cae-827c3ef472d2
  type: helm.sh/release.v1
kind: List
metadata:
  resourceVersion: ""
