apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2026-05-31T00:15:56Z"
    name: grpc-backend
    namespace: sample
    resourceVersion: "615"
    uid: 89758214-5a99-49b6-95f8-12a788b57973
  spec:
    clusterIP: 10.96.26.185
    clusterIPs:
    - 10.96.26.185
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: grpc
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      app: grpc-backend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: sample
      meta.helm.sh/release-namespace: sample
    creationTimestamp: "2026-05-31T00:15:56Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    name: sample
    namespace: sample
    resourceVersion: "632"
    uid: 36509614-ff02-4cb4-a24a-d544be262a48
  spec:
    clusterIP: 10.96.252.117
    clusterIPs:
    - 10.96.252.117
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: sample
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
