apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIfKVpHZKnmx8wDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjA2MDkxMzU0NTBaFw0zNjA2MDYxMzU5NTBaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQDC9WIHkUPIf2IJApEvfXJAXIJWVN6k7sprhQET6lO4bqqn+WjPO9Oz2ffV
      m+mp3kkl6oXfZCD9Yb5PMm6rfHLb/AGZZojqSRAijZ5YFExvK/+em+V/O7sZjl/g
      6DOnS2vGwRhAUl4Hsl8ZoyVcjoS0KYX9dIg1ZBpZ4jmT/YFLJw9S9KZbbOBgSkPi
      t0knrinRyMzsemSe5/seOoKUq+O7jkRLB00sYp5/B/O/dhxpAUCbNFrbX2cabbjn
      sTZwBv38APgCLgZ61T1cBL1NeJQtszEc4r+RvKQF6lqI5i+aXVEu4V4iqCGFa38Y
      zPAVDriJTIrv4DIoSy5jY5WwrK6vAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRmtnjd0yh9frWZ+XcvS8szkBtOzDAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQA5R8C4sigY
      07P3jiD7Fc/iE9mpjoS7TshjaAj572qbO0DfXlpgegcAD+UniwnAOMEW2OwjQ6Z6
      EL2u5FouWKLcwUzAq+0G9lyQaG+EOf57ThT3BMcdGkp0U7Uu6mHJiWUIm0FaBLps
      wjvPB2zJFOuR7GvruuQ6pGfnyoP8AUaLGFQivOiNOPoL5OGuVgFZvIPopKt9Zv+I
      RMPxXbc1H74mc+DiPaQljrL95XBV3DD6oLEvCLhO7H22ya909P4PUDmJdcZH5379
      G6y53UPzrTI7wQ7I3GnY1biameo5OmRaSjYKyXF8d0/BTP4RqBqMvt0Wpm/N5j/+
      Fn0kPEjxyM2y
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-06-09T14:00:54Z"
    name: kube-root-ca.crt
    namespace: sample
    resourceVersion: "591"
    uid: b36824bc-bd24-48f4-b18b-0f2280cb0ad7
kind: List
metadata:
  resourceVersion: ""
