scenario_id: ingress-controllers-traefik-tls-passthrough
scenario_path: /var/folders/10/9lylcxg10rd17gqmylhpw3740000gn/T/tmp.lghPzd6VVr/ingress-controllers-traefik-tls-passthrough.yaml
project_dir: /var/folders/10/9lylcxg10rd17gqmylhpw3740000gn
started_at: 2026-05-30T17:29:35Z
provider: kind
asserts:
