apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIPJ1SzqfWf48wDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjA2MDkxMzQ1NDJaFw0zNjA2MDYxMzUwNDJaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQDEyxnMrPEWX/N5/12oBRORCjLYLedyKkGoQ7z3eGj/SbZlB42ZjRdnFJuQ
      3QxPNHCcLbtHlrbR2QW/q71vTM8BJpHafCtJaNM+fpCZmEKc5zvbZzv9bkhaiQy+
      7K9I4XNnucMPpwh/X6lzYtWs3xzyTyIaiMhqX6+7VK6Vp16cnCURhS/P+JxtfvGI
      aWP3rzpJrMv7CfxNvOOWlk8JjNxj2Q8uFNe3C9rQFpXbSCr/e0L8B2xq8SvPsL8h
      1fxi/mdG+O9BSz5Uq89NOrjD10FBs9qJZrN0x+jdDBrB0v5TPwGb7e4SMhwXKDAD
      gKOqlW+gkF8IY84HK3p/07Ns8TCvAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBR9gRc1/puQapa4TUFE3vLYy6KJjjAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQBk7XLZlOAZ
      W6tK5nrnnqu7u1SqNQUJYlHp5Movc+SdatGlY2gx7gp90O0boFfkozudlP33arpj
      Y5SinYhsJx68VUrC/XVztEsgD1Ra937J87MQqSVeUzfuA2tzjTH1e4yh3ZNF1KZd
      Y7ES2c0b/u5ubJQE+2qhRjkHIs4T27f7CE5M0lSUMjqqtutbh2UPXHqnO4b4weFW
      H6j3YK77TzWH9he/AkqRXx1NLWtgk4i5BeSDtq2t8HKljHZPNHN3bu8nNA5SoUKB
      MdEftD17m9fI8PYaYRsENikwfmW4lnDieDlR0rcDmi5lnR4EANkCvbL/+5v0wf+l
      PTDVq0tVpfdB
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-06-09T13:51:43Z"
    name: kube-root-ca.crt
    namespace: sample
    resourceVersion: "664"
    uid: 98be0c6a-0afc-41bb-8b05-e852ec38e0ec
kind: List
metadata:
  resourceVersion: ""
