apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    creationTimestamp: "2026-06-09T13:51:43Z"
    generation: 1
    name: sample-basic
    namespace: sample
    resourceVersion: "667"
    uid: 3e38ce5e-df84-4b4c-9ce3-df3bb33cefb0
  spec:
    ingressClassName: nginx
    rules:
    - host: sample.test.local
      http:
        paths:
        - backend:
            service:
              name: sample
              port:
                number: 80
          path: /
          pathType: Prefix
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
