apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIWjGSq2oNGEEwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjA2MDkxMjUxNDRaFw0zNjA2MDYxMjU2NDRaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQC50Ir05iTBcWcNZKOFmrS97wwewlJhJsfFV6yd6yFnmXWbta9Qm/eE8gIU
      60iP9nL3fY01BgXMOuMvhJHYn+puSPsopoiB1dsjTg8p12zd6VlD9r2GJIoJ0CKN
      v9HPQdVsjSZgJDt5VYEGrILggOawxDSMAoLpHVTS8PjH0qA0x4ApAjiR1O+nux2T
      Nwoqax2OggsjBWiZLNqRBhUnwlTLW+LCdZXRxK+hP1EyR+gsc30Rf/zCTOqou5k0
      P//CX0fUW5q4lZx0m4BICUJR2h+M6sOhQAS3hEVgjRKfRKwk9xBlhuuWKCCHg9pl
      /P9Usi0IH6PVedYA89BuNp6pFIGLAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQrY7kUprWLOXnOyy8hDARefANjDTAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQB5fd5/wAVP
      2+RXTIrTuQDhT2g5JfwSX3Fdp2AYQ7OtbrdJJAAVRFFXjBrge+LncsmL00EYnHwO
      ljr14M6mEV3Lo6oFQ97hsTjR7aitxS+EFC9RW863OAN2CNDkRZeho+MfWF1GRG0+
      JDaMHraySqtd3zraFvUd08IR7eDiFecprq4bAioTvuqfwL9anWhfPNRR+YntHeTT
      hvfCn321tEC/U/l3waedn3PDcJynJFnfN197EyeUFxpDbj1JXAh8wHMaQy1A+gww
      ELTOvzuf3o1FMCMutpWwvQkdiBfEft7QJRlTXaOo5aehbnDcN76v0reQsxe5ozu7
      KCAbs6DrS4T5
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-06-09T12:57:09Z"
    name: kube-root-ca.crt
    namespace: sample
    resourceVersion: "406"
    uid: 8e419987-ac10-4e4c-8289-c4b50067a99f
kind: List
metadata:
  resourceVersion: ""
